/**
 * COMPLETE translation script — covers ALL 1448 auto keys.
 * Resets en.auto to Arabic, then applies full sentence-level translations.
 */
const fs = require('fs');
const path = require('path');

const localesDir = path.resolve(__dirname, '../apps/web/src/i18n/locales');
const arFile = path.join(localesDir, 'ar.json');
const enFile = path.join(localesDir, 'en.json');
const urFile = path.join(localesDir, 'ur.json');

const ar = JSON.parse(fs.readFileSync(arFile, 'utf8'));
const en = JSON.parse(fs.readFileSync(enFile, 'utf8'));
const ur = JSON.parse(fs.readFileSync(urFile, 'utf8'));

if (!en.auto) en.auto = {};
if (!ur.auto) ur.auto = {};

// Step 1: Reset ALL auto keys to Arabic source
for (const [key, arVal] of Object.entries(ar.auto || {})) {
  en.auto[key] = arVal;
  ur.auto[key] = arVal;
}

// Step 2: COMPLETE Arabic -> English map
const enMap = {
  // ============================================================
  // SINGLE WORDS / SHORT LABELS
  // ============================================================
  'د': 'min',
  'س': 'hr',
  'م²': 'm²',
  'عام': 'General',
  'معطل': 'Disabled',
  'نشطة': 'Active',
  'معطلة': 'Disabled',
  'مكتمل': 'Completed',
  'معلق': 'Pending',
  'مرفوض': 'Rejected',
  'عاجل': 'Urgent',
  'عادي': 'Normal',
  'حاضر': 'Present',
  'متأخر': 'Late',
  'غائب': 'Absent',
  'معذور': 'Excused',
  'يدوي': 'Manual',
  'إكسيل': 'Excel',
  'الشركة': 'Company',
  'وثيقة': 'Document',
  'تجاوز': 'Override',
  'الإصدار': 'Version',
  'الفئة': 'Category',
  'المصدر': 'Source',
  'التصنيف': 'Classification',
  'التاريخ': 'Date',
  'الحالة': 'Status',
  'حضور': 'Attendance',
  'انصراف': 'Departure',
  'إضافي': 'Overtime',
  'الإجمالي': 'Total',
  'صالح': 'Valid',
  'مكرر': 'Duplicate',
  'الاسم': 'Name',
  'الأجر': 'Wage',
  'الدور': 'Role',
  'الكمية': 'Quantity',
  'البند': 'Item',
  'المرحلة': 'Stage',
  'المشروع': 'Project',
  'الفرع': 'Branch',
  'النوع': 'Type',
  'تنبيه': 'Alert',
  'تحذير': 'Warning',
  'إشعار': 'Notification',
  'اعتماد': 'Approval',
  'إنتاج': 'Production',
  'إنتاجية': 'Productivity',
  'نقل': 'Transfer',
  'بصمة': 'Fingerprint',
  'مستند': 'Document',
  'ريال': 'SAR',
  'ساعة': 'hour',
  'ساعات': 'hours',
  'يوم': 'day',
  'موظف': 'Employee',
  'عامل': 'Worker',
  'مشرف': 'Supervisor',
  'مشروع': 'Project',
  'فرع': 'Branch',
  'موقع': 'Site',
  'فردي': 'Individual',
  'فريق': 'Team',
  'مرحلة': 'Stage',
  'بند': 'Item',
  'قسم': 'Department',
  'سجل': 'Record',
  'مستخدم': 'User',
  'المشروع:': 'Project:',
  'الفرع:': 'Branch:',
  'المشرف': 'Supervisor',
  'اليوم': 'Today',
  'أخرى': 'Other',
  'الآن': 'Now',
  'صح': 'Correct',
  'المستخدم': 'User',
  'مستوى': 'Level',

  // ============================================================
  // ATTENDANCE POLICIES
  // ============================================================
  'Current password is wrong / كلمة المرور الحالية غير صحيحة': 'Current password is wrong',
  'فشل تحميل سياسات الحضور والدوام': 'Failed to load attendance policies',
  'تم تحديث سياسة الحضور بنجاح': 'Attendance policy updated successfully',
  'تم إنشاء سياسة الحضور الجديدة بنجاح': 'New attendance policy created successfully',
  'فشل حفظ سياسة الحضور': 'Failed to save attendance policy',
  'هل أنت متأكد من رغبتك في إلغاء/حذف هذه السياسة؟': 'Are you sure you want to cancel/delete this policy?',
  'تم إلغاء تنشيط السياسة بنجاح': 'Policy deactivated successfully',
  'فشل حذف السياسة': 'Failed to delete policy',
  'إدارة وتخصيص سياسات الحضور والدوام': 'Manage & Customize Attendance Policies',
  'إغلاق': 'Close',
  'إلغاء': 'Cancel',
  'حفظ تعديلات السياسة': 'Save Policy Changes',
  'حفظ وإنشاء السياسة': 'Save & Create Policy',
  'سياسات الدوام الحالية': 'Current Work Shift Policies',
  'إضافة سياسة جديدة': 'Add New Policy',
  'جاري تحميل السياسات...': 'Loading policies...',
  'لا توجد سياسات مسجلة حالياً': 'No policies registered currently',
  '🏢 السياسة العامة للمنشأة': '🏢 Company General Policy',
  'مشروع مخصص': 'Custom Project',
  'سارية من:': 'Effective from:',
  'مواعيد الدوام:': 'Work schedule:',
  'فترة السماح:': 'Grace period:',
  'دقيقة': 'minute',
  'الاستراحة:': 'Break:',
  'بدء الإضافي بعد:': 'Overtime starts after:',
  '(معامل ×': '(Multiplier ×',
  'تعديل': 'Edit',
  'حذف / تعطيل': 'Delete / Disable',
  'تعديل سياسة الحضور': 'Edit Attendance Policy',
  'إضافة سياسة حضور جديدة': 'Add New Attendance Policy',
  'إلغاء والعودة للقائمة': 'Cancel & Return to List',
  'نطاق السياسة (المشروع أو عام)': 'Policy Scope (Project or General)',
  '🏢 السياسة العامة لجميع مشاريع المنشأة': '🏢 General Policy for All Company Projects',
  'معامل احتساب الساعة الإضافية': 'Overtime Hour Multiplier',
  'يرجى اختيار ملف بصمة أولاً': 'Please select a fingerprint file first',
  'فشل قراءة وتحليل ملف البصمة': 'Failed to read and analyze fingerprint file',
  'رفع ملف آخر': 'Upload Another File',
  'تحليل الملف ومطابقة السياسة': 'Analyze File & Match Policy',
  'اسحب وأفلت شيت إكسيل البصمة هنا أو انقر للاختيار': 'Drag & drop fingerprint Excel sheet here or click to select',
  'دوام:': 'Shift:',
  'إضافي بعد:': 'Overtime after:',
  'الكل (': 'All (',
  '✓ صالح للاستيراد (': '✓ Valid for import (',
  '⚠️ أخطاء وتكرار (': '⚠️ Errors & duplicates (',
  'بحث بالاسم أو الكود...': 'Search by name or code...',
  'الموظف / كود البصمة': 'Employee / Fingerprint Code',
  'التاريخ': 'Date',
  'الحالة': 'Status',
  'تبديل القائمة': 'Toggle Menu',
  'العملة: SAR': 'Currency: SAR',
  'تسجيل الخروج': 'Logout',
  'خروج': 'Logout',

  // ============================================================
  // NAVIGATION / SIDEBAR
  // ============================================================
  'المقايسة وتقدم التنفيذ': 'BOQ & Execution Progress',
  'الإنتاجية اليومية': 'Daily Productivity',
  'الحضور والانصراف': 'Attendance & Departure',
  'الحوافز والمكافآت': 'Incentives & Bonuses',
  'المستندات والأرشيف': 'Documents & Archive',
  'نظرة عامة': 'Overview',
  'لوحة التحكم': 'Dashboard',
  'بطاقات التحكم': 'Control Cards',
  'التقرير اليومي': 'Daily Report',
  'عمليات الموقع': 'Site Operations',
  'مناطق العمل (الهيكل)': 'Work Areas (Structure)',
  'نقل الكوادر والمشرفين': 'Staff & Supervisor Transfer',
  'الموارد والبيانات': 'Resources & Data',
  'الموظفون والعمال': 'Employees & Workers',
  'الفروع': 'Branches',
  'المشاريع': 'Projects',
  'بنود الأعمال (BOQ)': 'Work Items (BOQ)',
  'المالية': 'Finance',
  'التكاليف والمصروفات': 'Costs & Expenses',
  'المستندات والتقارير': 'Documents & Reports',
  'التقارير والمؤشرات': 'Reports & Indicators',
  'قواعد التنبيهات الميدانية': 'Field Alert Rules',
  'النظام والأمان': 'System & Security',
  'مركز الإشعارات والتنبيهات': 'Notifications & Alerts Center',
  'إدارة الحسابات والمستخدمين': 'Account & User Management',
  'الصلاحيات (RBAC)': 'Permissions (RBAC)',
  'الإعدادات': 'Settings',
  'قريبًا': 'Coming Soon',
  'العملة': 'Currency',
  'متصل': 'Online',
  'جاري التحقق من بيانات الجلسة...': 'Verifying session data...',

  // ============================================================
  // ALERTS & NOTIFICATIONS
  // ============================================================
  'فشل تحميل بيانات التنبيهات': 'Failed to load alert data',
  'فشل تحديث حالة الإشعارات': 'Failed to update notification status',
  'إضافة قاعدة تنبيه': 'Add Alert Rule',
  'مركز الإشعارات': 'Notification Center',
  'تحديد الكل كمقروء': 'Mark All as Read',
  'إنشاء القاعدة': 'Create Rule',
  'اسم القاعدة *': 'Rule Name *',
  'الوحدة': 'Unit',
  '%, يوم, SAR': '%, day, SAR',
  'السجلات': 'Records',
  'بند عمل': 'Work Item',
  'فشل تحميل الإشعارات': 'Failed to load notifications',
  'فشل تحديث الإشعار': 'Failed to update notification',
  'إشعار نظام': 'System Notification',

  // ============================================================
  // ATTENDANCE
  // ============================================================
  'فشل تحميل سجلات الحضور': 'Failed to load attendance records',
  'تم تسجيل الحضور بنجاح': 'Attendance recorded successfully',
  'فشل تسجيل الحضور': 'Failed to record attendance',
  'ساعات إضافي اليوم': 'Overtime hours today',
  'نطاق مخصص': 'Custom Range',
  'كافة المشاريع': 'All Projects',
  'الفرع': 'Branch',
  'كافة الفروع': 'All Branches',
  'من تاريخ': 'From Date',
  'من تاريخ...': 'From date...',
  'إلى تاريخ': 'To Date',
  'إلى تاريخ...': 'To date...',
  'الموظف / العامل': 'Employee / Worker',
  'المشروع والفرع': 'Project & Branch',
  'حالة الحضور': 'Attendance Status',
  'ساعات الإضافي': 'Overtime Hours',
  'عرض': 'View',
  'من إجمالي': 'of total',
  'سجل حضور': 'Attendance record',
  'السابق': 'Previous',
  'التالي': 'Next',
  'تسجيل حضور موظف': 'Record Employee Attendance',
  'تسجيل الحضور': 'Record Attendance',
  'الموظف / العامل *': 'Employee / Worker *',
  'التاريخ *': 'Date *',
  'حالة الحضور *': 'Attendance Status *',
  'حاضر (Present)': 'Present',
  'غائب (Absent)': 'Absent',
  'متأخر (Late)': 'Late',
  'تم استيراد واعتماد سجلات البصمة بنجاح': 'Fingerprint records imported and approved successfully',

  // ============================================================
  // BOQ
  // ============================================================
  'فشل تحميل بيانات المقايسة': 'Failed to load BOQ data',
  'إجمالي بنود المقايسة': 'Total BOQ Items',
  'بدون كود': 'No code',
  'نسبة الإنجاز': 'Completion Rate',
  'بند مقايسة': 'BOQ Item',
  'وحدة': 'Unit',

  // ============================================================
  // BRANCHES
  // ============================================================
  'فشل تحميل بيانات الفروع': 'Failed to load branch data',
  'تم تحديث بيانات الفرع بنجاح': 'Branch data updated successfully',
  'فشل حفظ بيانات الفرع': 'Failed to save branch data',
  'فشل حذف الفرع': 'Failed to delete branch',
  'اسم الفرع': 'Branch Name',
  'كود الفرع': 'Branch Code',
  'الإجراءات': 'Actions',
  'نشط': 'Active',
  'تعديل الفرع': 'Edit Branch',
  'حذف الفرع': 'Delete Branch',
  'تأكيد حذف الفرع': 'Confirm Branch Deletion',
  'هل أنت متأكد من رغبتك في حذف الفرع': 'Are you sure you want to delete this branch',
  'تعديل بيانات الفرع': 'Edit Branch Data',
  'إضافة فرع جديد': 'Add New Branch',
  'حفظ التعديلات': 'Save Changes',
  'إنشاء الفرع': 'Create Branch',

  // ============================================================
  // WIP PAGES
  // ============================================================
  'نظام الحوافز والمكافآت والإنتاجية': 'Incentives, Bonuses & Productivity System',
  'نظام حساب المكافآت التلقائي للكوادر الفنية والمشرفين بناءً على تجاوز معدلات الإنتاجية القياسية ونسب إنجاز مراحل البنود في الوقت المحدد.': 'Automatic bonus calculation system for technical staff and supervisors based on exceeding standard productivity rates and item stage completion within schedule.',
  'جاهز برمجياً في الـ Backend ومربوط ببيانات الإنتاج والحضور': 'Backend ready and linked to production and attendance data',
  'حساب البونص التلقائي لكل متر/وحدة إضافية فوق المستهدف': 'Automatic bonus calculation per extra meter/unit above target',
  'صرف حوافز إنجاز المراحل الحرجة قبل الموعد التعاقدي': 'Critical stage completion incentive disbursement before contract deadline',
  'تقارير تفصيلية لمكافآت المشرفين والفرق الميدانية': 'Detailed bonus reports for supervisors and field teams',
  'المستندات والأرشيف السحابي والمخططات': 'Documents, Cloud Archive & Drawings',
  'أرشيف رقمي منظم لكافة مخططات الـ Shop Drawings، محاضر الاستلام، كراسات الشروط، ومستندات المشاريع مع إدارة الإصدارات والصلاحيات.': 'Organized digital archive for all Shop Drawings, handover minutes, specification books, and project documents with version and permission management.',
  'جاهز برمجياً في الـ Backend مع التوثيق والمرفقات': 'Backend ready with documentation and attachments',
  'أرشفة مخططات الـ PDF والتصميمات المعمارية والإنشائية': 'Archive PDF drawings and architectural/structural designs',
  'إدارة أذونات ومحاضر فحص واستلام الاستشاري': 'Manage permits and consultant inspection/handover records',
  'ربط المستندات ببند الـ BOQ أو منطقة العمل المعنية': 'Link documents to BOQ items or relevant work areas',
  'مركز التقارير المتقدمة والتحليلات الشاملة': 'Advanced Reports & Comprehensive Analytics Center',
  'مركز شامل لاستخراج التقارير المالية والإنتاجية التنفيذية، مؤشرات الأداء الرئيسية (KPIs)، وتصدير المخططات التفصيلية.': 'Comprehensive center for extracting financial and production execution reports, Key Performance Indicators (KPIs), and exporting detailed charts.',
  'التقرير اليومي متاح حالياً، وجاري تجهيز لوحة التحليلات المتقدمة': 'Daily report is currently available, advanced analytics dashboard is being prepared',
  'تقرير الإنتاجية والمقارنات بين المشاريع والفروع': 'Productivity report and comparisons between projects and branches',
  'تحليل انحراف التكاليف والموازنات التقديرية': 'Cost deviation and estimated budget analysis',
  'تصدير كشوفات الإنجاز لملفات Excel و PDF متقدمة': 'Export completion statements to advanced Excel and PDF files',
  'إعدادات النظام والتهيئة العامة': 'System Settings & General Configuration',
  'شاشة التحكم في إعدادات المنظومة، إدارة المستخدمين، التهيئة العامة للشركة، ربط السيرفرات والنسخ الاحتياطي.': 'System settings control screen, user management, company general configuration, server linking and backup.',
  'إدارة الأدوار والمستخدمين مفعلة من خلال قاعدة البيانات': 'Role and user management enabled through database',
  'تخصيص بيانات الشركة والترويسة الرسمية': 'Customize company data and official letterhead',
  'إدارة صلاحيات المستخدمين وهيكل الأدوار الهرمي': 'Manage user permissions and hierarchical role structure',
  'تهيئة أوقات الدوام الرسمي ومعدلات الإضافي والتنبيهات': 'Configure official work hours, overtime rates and alerts',
  'الصفحة قيد التطوير والتجهيز': 'Page Under Development',
  'مجدولة ضمن خطة التطوير': 'Scheduled in the development plan',
  'واجهة تفاعلية حديثة': 'Modern interactive interface',
  'ربط مباشر مع قاعدة البيانات': 'Direct database connection',
  'تصدير التقارير والإحصائيات': 'Export reports and statistics',

  // ============================================================
  // CONTROL CARDS (extra)
  // ============================================================
  'تسجيل الإنتاجية': 'Record Productivity',
  'تعديل المراحل': 'Edit Stages',
  'مرحلة التنفيذ': 'Execution Stage',
  '/يوم': '/day',
  '2. معدلات الإنتاجية المستهدفة': '2. Target Productivity Rates',
  '/ساعة': '/hour',
  '* الحساب:': '* Calculation:',
  'ريال/يوم': 'SAR/day',
  'ريال/': 'SAR/',
  'يوم عمل': 'work day',
  'مستهدف اليوم': 'Today\'s target',

  // ============================================================
  // COSTS
  // ============================================================
  'فشل تحميل بيانات التكاليف': 'Failed to load cost data',
  'الكمية × السعر': 'Quantity × Price',
  'بدون تخصيص مشروع': 'Without project assignment',
  'بدون تخصيص فرع': 'Without branch assignment',
  'الكمية': 'Quantity',
  'سعر الوحدة (SAR)': 'Unit Price (SAR)',
  'من تاريخ *': 'From Date *',
  'إلى تاريخ *': 'To Date *',
  'عرض الكل': 'Show All',
  'عرض الكل (': 'Show All (',
  'اسم البند': 'Item Name',

  // ============================================================
  // DOCUMENTS
  // ============================================================
  'فشل تحميل قائمة المستندات': 'Failed to load document list',
  'فشل رفع المستند': 'Failed to upload document',
  'فشل تحميل الملف': 'Failed to download file',
  'فشل حذف المستند': 'Failed to delete document',
  'رفع مستند جديد': 'Upload New Document',
  'تحميل الملف': 'Download File',
  'حذف المستند': 'Delete Document',
  'رفع مستند جديد إلى الأرشيف': 'Upload New Document to Archive',
  'ملاحظات:': 'Notes:',
  'هل أنت متأكد من رغبتك في حذف المستند': 'Are you sure you want to delete the document',

  // ============================================================
  // EMPLOYEES
  // ============================================================
  'تعديل بيانات الموظف / العامل': 'Edit Employee / Worker Data',
  'إضافة موظف / عامل جديد': 'Add New Employee / Worker',
  'إضافة الموظف': 'Add Employee',
  '10xxxxxxxx أو 23xxxxxxxx': '10xxxxxxxx or 23xxxxxxxx',
  'الجنسية': 'Nationality',
  'مشرف تنفيذ (Supervisor)': 'Execution Supervisor',
  'رقم الجوال': 'Mobile Number',
  'فشل تحميل بيانات الموظفين': 'Failed to load employee data',
  'تم تحديث بيانات الموظف بنجاح': 'Employee data updated successfully',
  'فشل حفظ بيانات الموظف': 'Failed to save employee data',
  'فشل تعطيل الموظف': 'Failed to deactivate employee',
  'تم تصدير ملف الموظفين بنجاح': 'Employee file exported successfully',
  'فشل تصدير ملف الموظفين': 'Failed to export employee file',
  'إجمالي الموظفين': 'Total Employees',
  'منتهية (': 'Expired (',
  'يوم مضت)': 'days ago)',
  'تنتهي خلال': 'Expires in',
  'فحص هوية / إقامة فوري:': 'Instant ID / Iqama Check:',
  'أدخل رقم الهوية أو الإقامة...': 'Enter ID or Iqama number...',
  'استعلام': 'Lookup',
  '✓ وُجد:': '✓ Found:',
  'بحث بالاسم أو الكود': 'Search by name or code',
  'الدور الوظيفي': 'Job Role',
  'كافة الأدوار': 'All Roles',
  'عامل (Worker)': 'Worker',
  'مشرف (Supervisor)': 'Supervisor',
  'مهندس (Engineer)': 'Engineer',
  'مدير مشروع': 'Project Manager',
  'نشط فقط': 'Active Only',
  'معطل فقط': 'Disabled Only',
  'الاسم / الكود': 'Name / Code',
  'الوثيقة / رقم الهوية': 'Document / ID Number',
  'صلاحية الإقامة / الهوية': 'Iqama / ID Validity',
  'الأجر اليومي': 'Daily Wage',
  'لا يوجد موظفون مطابقون لمعايير البحث': 'No employees matching search criteria',
  'SAR/يوم': 'SAR/day',
  'عرض التعيينات': 'View Assignments',
  'تعديل الموظف': 'Edit Employee',
  'تعطيل / حذف': 'Disable / Delete',
  'موظف/عامل': 'Employee/Worker',
  'تم استيراد واعتماد بيانات الموظفين بنجاح!': 'Employee data imported and approved successfully!',
  'تأكيد تعطيل الموظف': 'Confirm Employee Deactivation',
  'تأكيد التعطيل': 'Confirm Deactivation',
  'هل أنت متأكد من رغبتك في تعطيل الموظف': 'Are you sure you want to deactivate employee',
  '؟ (Soft Delete - يمكن إعادة تنشيطه لاحقًا).': '? (Soft Delete - can be reactivated later).',
  'كود:': 'Code:',
  '• دور:': '• Role:',
  'منذ': 'Since',
  'لا توجد تعيينات حالية لهذا الموظف': 'No current assignments for this employee',

  // ============================================================
  // EMPLOYEE IMPORT
  // ============================================================
  'يرجى اختيار ملف إكسيل (.xlsx)': 'Please select an Excel file (.xlsx)',
  'فشل رفع ومعالجة ملف الإكسيل': 'Failed to upload and process Excel file',
  'تم اعتماد وإدراج بيانات الموظفين الصالحة بنجاح!': 'Valid employee data approved and inserted successfully!',
  'فشل اعتماد البيانات المستوردة': 'Failed to approve imported data',
  'استيراد بيانات الموظفين من ملف Excel (.xlsx)': 'Import Employee Data from Excel (.xlsx)',
  'رفع وتحليل الملف': 'Upload & Analyze File',
  'اعتماد السجلات الصالحة (': 'Approve Valid Records (',
  'اختر ملف Excel (.xlsx) لرفعه وفحصه': 'Select Excel (.xlsx) file to upload and check',
  'يتم فحص الأعمدة والهويات وتوليد تقرير مرحلي قبل إدراج البيانات في قاعدة البيانات': 'Columns and IDs are checked and a staged report is generated before inserting data into the database',
  'رقم الهوية': 'ID Number',
  'مكرر (Duplicate)': 'Duplicate',
  'غير صالح (Invalid)': 'Invalid',

  // ============================================================
  // INCENTIVES
  // ============================================================
  'فشل تحميل قواعد الحوافز': 'Failed to load incentive rules',
  'فشل تحميل سجل استحقاقات الحوافز': 'Failed to load incentive entitlements record',
  'تم احتساب الحوافز: لا توجد سجلات مستحقة تطابق شروط القواعد في هذه الفترة.': 'Incentives calculated: no eligible records matching rule conditions in this period.',
  'فشل احتساب الحوافز': 'Failed to calculate incentives',
  'يرجى تحديد بند واحد على الأقل للاعتماد': 'Please select at least one item for approval',
  'فشل اعتماد الحوافز': 'Failed to approve incentives',
  'تم تحديث حالة الاستحقاق إلى "مدفوع" بنجاح.': 'Entitlement status updated to "Paid" successfully.',
  'فشل تحديث حالة الاستحقاق': 'Failed to update entitlement status',
  'اسم القاعدة مطلوب': 'Rule name is required',
  'تم تحديث قاعدة الحوافز بنجاح.': 'Incentive rule updated successfully.',
  'تم إنشاء قاعدة الحوافز الجديدة بنجاح.': 'New incentive rule created successfully.',
  'فشل حفظ قاعدة الحوافز': 'Failed to save incentive rule',
  'تم حذف قاعدة الحوافز بنجاح.': 'Incentive rule deleted successfully.',
  'فشل حذف قاعدة الحوافز': 'Failed to delete incentive rule',
  'حافز تجاوز الإنتاجية': 'Productivity Overachievement Incentive',
  'مكافأة جودة وأداء': 'Quality & Performance Bonus',
  'حافز انتظام الحضور': 'Attendance Regularity Incentive',
  'تم الصرف (مدفوع)': 'Disbursed (Paid)',
  'معتمد ومستحق': 'Approved & Due',
  'قيد المعالجة (معلق)': 'Processing (Pending)',
  'إجمالي الحوافز المرصودة': 'Total Allocated Incentives',
  'مستحقات بانتظار الصرف': 'Entitlements Awaiting Disbursement',
  'معتمدة وجاهزة للتحويل': 'Approved and ready for transfer',
  'المصروف والمسدد للعمالة': 'Disbursed & Paid to Workers',
  'تم تحويله لحسابات المستفيدين': 'Transferred to beneficiary accounts',
  'قواعد الحوافز النشطة': 'Active Incentive Rules',
  'احتساب الحوافز من الإنتاجية': 'Calculate Incentives from Productivity',
  'إضافة قاعدة حوافز': 'Add Incentive Rule',
  'سجل الاستحقاقات والصرف (': 'Entitlements & Disbursement Record (',
  'محرك الاحتساب والاعتماد': 'Calculation & Approval Engine',
  'قواعد ومعادلات الحوافز (': 'Incentive Rules & Formulas (',
  'تصفية بحسب حالة الصرف': 'Filter by Disbursement Status',
  'معتمد ومستحق (Approved)': 'Approved & Due',
  'تم الصرف (Paid)': 'Disbursed (Paid)',
  'قيد المعالجة (Pending)': 'Processing (Pending)',
  'المستفيد / العامل': 'Beneficiary / Worker',
  'القاعدة والمبرر': 'Rule & Justification',
  'قيمة الحافز (SAR)': 'Incentive Value (SAR)',
  'لا توجد استحقاقات مسجلة بسجل الحوافز': 'No entitlements registered in incentives record',
  'عام / غير محدد': 'General / Unspecified',
  'حافز تشغيلي': 'Operational Incentive',
  'تسجيل كمدفوع': 'Mark as Paid',
  'تم السداد ✓': 'Paid ✓',
  'استحقاق': 'Entitlement',
  'فترة احتساب الأداء والإنتاجية': 'Performance & Productivity Calculation Period',
  'تشغيل احتساب الحوافز الآن': 'Run Incentive Calculation Now',
  'نتائج الاحتساب:': 'Calculation Results:',
  'استحقاق بقيمة إجمالية': 'Entitlement with total value',
  'حدد البنود المراد اعتمادها ثم انقر زر الاعتماد والترحيل لسجل الحوافز': 'Select items to approve then click the approve and post button for incentives record',
  'إلغاء تحديد الكل': 'Deselect All',
  'تحديد الكل': 'Select All',
  'اعتماد وصرف الحوافز المحددة (': 'Approve & Disburse Selected Incentives (',
  'القاعدة المطبقة': 'Applied Rule',
  'المبرر ونسبة الإنجاز': 'Justification & Completion Rate',
  'المكافأة المستحقة (SAR)': 'Due Bonus (SAR)',
  'نسبة الإنجاز المحققة:': 'Achieved Completion Rate:',
  'اسم القاعدة': 'Rule Name',
  'النوع والمسار': 'Type & Path',
  'الحد المستهدف (% أو أيام)': 'Target Threshold (% or days)',
  'مبلغ المكافأة (SAR)': 'Bonus Amount (SAR)',
  'لا توجد قواعد حوافز معرفة بعد. انقر "إضافة قاعدة حوافز" للبدء.': 'No incentive rules defined yet. Click "Add Incentive Rule" to start.',
  'نشطة ومطبقة': 'Active & Applied',
  'معطلة مؤقتًا': 'Temporarily Disabled',
  'تعديل القاعدة': 'Edit Rule',
  'حذف القاعدة': 'Delete Rule',
  'تعديل قاعدة الحوافز': 'Edit Incentive Rule',
  'إضافة قاعدة حوافز جديدة': 'Add New Incentive Rule',
  'مثال: حافز إنجاز صب الخرسانة 120%': 'Example: 120% concrete pouring completion incentive',
  'نوع الحافز': 'Incentive Type',
  'حافز تجاوز الإنتاجية (Production Bonus)': 'Productivity Overachievement Bonus',
  'مكافأة جودة وأداء (Quality Bonus)': 'Quality & Performance Bonus',
  'حافز انتظام الحضور (Attendance Bonus)': 'Attendance Regularity Bonus',
  'الحد الأدنى المستهدف (%)': 'Minimum Target (%)',
  'تفعيل القاعدة في محرك الاحتساب التلقائي': 'Activate rule in automatic calculation engine',
  'تأكيد حذف قاعدة الحوافز': 'Confirm Incentive Rule Deletion',
  'هل أنت متأكد من رغبتك في حذف القاعدة': 'Are you sure you want to delete the rule',
  '؟': '?',

  // ============================================================
  // NOTIFICATIONS
  // ============================================================
  'تم تحديث حالة الإشعار إلى مقروء.': 'Notification status updated to read.',
  'تم تعليم كافة الإشعارات كمقروءة بنجاح.': 'All notifications marked as read successfully.',
  'فشل تعليم الإشعارات كمقروءة': 'Failed to mark notifications as read',
  'طلب اعتماد': 'Approval Request',
  'طلب نقل': 'Transfer Request',
  'إجمالي الإشعارات المسجلة': 'Total Registered Notifications',
  'إشعارات جديدة غير مقروءة': 'New Unread Notifications',
  'تتطلب اهتمام المستخدم': 'Require user attention',
  'تمت قراءة جميع الإشعارات': 'All notifications have been read',
  'تنبيهات ومخاطر ميدانية': 'Field Alerts & Risks',
  'تحذيرات تجاوز التكاليف والإنتاجية': 'Cost & Productivity Overrun Warnings',
  'أمان وتتبع العمليات': 'Security & Operations Tracking',
  'تنبيهات فورية على مدار الساعة': '24/7 Instant Alerts',
  'حالة القراءة': 'Read Status',
  'كافة الإشعارات (المقروءة والجديدة)': 'All Notifications (Read & New)',
  'غير المقروءة فقط (الجديدة)': 'Unread Only (New)',
  'المقروءة سابقاً': 'Previously Read',
  'نوع الإشعار': 'Notification Type',
  'كافة الأنواع': 'All Types',
  'تنبيهات عاجلة (Alerts)': 'Urgent Alerts',
  'تحذيرات الموقع (Warnings)': 'Site Warnings',
  'طلبات اعتماد (Approvals)': 'Approval Requests',
  'طلبات نقل (Transfers)': 'Transfer Requests',
  'إشعارات عامة (Info)': 'General Notifications (Info)',
  'عنوان الإشعار': 'Notification Title',
  'التفاصيل والمحتوى': 'Details & Content',
  'التاريخ والتوقيت': 'Date & Time',
  'لا توجد إشعارات مطابقة للمرشحات': 'No notifications matching filters',
  'تعليم كمقروء': 'Mark as Read',
  'تحديد كمقروء': 'Mark as Read',
  'تفاصيل الإشعار': 'Notification Details',
  'النوع:': 'Type:',
  'التوقيت:': 'Time:',

  // ============================================================
  // PRODUCTION APPROVAL WORKFLOW
  // ============================================================
  'إنشاء المسودة': 'Create Draft',
  'مُسجل الإنتاج': 'Production Recorder',
  'المسؤول الميداني': 'Field Officer',
  'تقديم السجل للاعتماد': 'Submit Record for Approval',
  'مسؤول الموقع': 'Site Officer',
  'اعتماد المشرف الميداني': 'Field Supervisor Approval',
  'مشرف التنفيذ (Supervisor)': 'Execution Supervisor',
  'اعتماد المهندس المسؤول': 'Responsible Engineer Approval',
  'مهندس الموقع (Engineer)': 'Site Engineer',
  'الاعتماد النهائي والإغلاق': 'Final Approval & Closure',
  'مدير المشروع / الإدارة (Admin)': 'Project Manager / Admin',
  'الإدارة المركزية': 'Central Management',
  'مسار ودورة الاعتمادات الصارمة (State Machine Timeline)': 'Strict Approval Workflow (State Machine Timeline)',
  'سبب الرفض / الإعادة:': 'Rejection / Return Reason:',
  'في الانتظار': 'Pending',
  'المرحلة الحالية': 'Current Stage',
  '✓ مكتمل': '✓ Completed',
  'بواسطة:': 'By:',

  // ============================================================
  // PRODUCTION CORRECTION
  // ============================================================
  'يرجى كتابة سبب طلب التصحيح': 'Please write the correction request reason',
  'تم تقديم طلب التصحيح بنجاح، بانتظار الاعتماد!': 'Correction request submitted successfully, awaiting approval!',
  'خطأ: لا يمكن تقديم طلب تصحيح إلا للسجلات المعتمدة نهائيًا والمغلقة (final_approved)': 'Error: Correction requests can only be submitted for final approved and closed records',
  'فشل تقديم طلب التصحيح': 'Failed to submit correction request',
  'طلب تعديل / تصحيح إنتاج مغلق': 'Closed Production Edit / Correction Request',
  'تقديم طلب التصحيح': 'Submit Correction Request',
  'السجل معتمد ومغلق. التصحيح يضاف كقيد إضافي تراكمي (Additive Correction) بعد الاعتماد.': 'Record is approved and closed. Correction is added as a cumulative additive entry after approval.',
  'نوع التصحيح المطلوب *': 'Required Correction Type *',
  'تعديل كمية (Quantity Adjustment)': 'Quantity Adjustment',
  'إلغاء السجل (Annul)': 'Annul Record',
  'إضافة ملاحظة تصحيحية (Note)': 'Add Correction Note',
  'فارق الكمية (Delta) *': 'Quantity Delta *',
  '(يمكن أن يكون موجب + أو سالب -)': '(Can be positive + or negative -)',
  'مثال: +15 أو -5.5': 'Example: +15 or -5.5',
  'سبب طلب التصحيح والمبرر الهندسي *': 'Correction Request Reason & Engineering Justification *',
  'يرجى كتابة سبب التعديل وتفاصيل المعاينة الميدانية...': 'Please write the edit reason and field inspection details...',

  // ============================================================
  // PRODUCTION DETAILS
  // ============================================================
  'تمت ترقية واعتماد مرحلة السجل بنجاح!': 'Record stage promoted and approved successfully!',
  'فشل تنفيذ عملية الاعتماد': 'Failed to execute approval process',
  'تفاصيل تقرير الإنتاجية اليومي': 'Daily Productivity Report Details',
  'طلب تصحيح (Correction Request)': 'Correction Request',
  'تقديم السجل للاعتماد (Submit)': 'Submit Record for Approval',
  'يتطلب دور مشرف معتمد (Supervisor)': 'Requires approved Supervisor role',
  'اعتماد المشرف (Supervisor Approve)': 'Supervisor Approval',
  'يتطلب دور مهندس معتمد (Engineer)': 'Requires approved Engineer role',
  'اعتماد المهندس (Engineer Approve)': 'Engineer Approval',
  'يتطلب صلاحية مدير النظام (Admin)': 'Requires System Admin permission',
  'الاعتماد النهائي والإغلاق (Final Approve)': 'Final Approval & Closure',
  'الفرع والمشروع': 'Branch & Project',
  'بند وموقع العمل': 'Item & Work Site',
  'كامل الموقع': 'Entire Site',
  'المشرف المسؤول': 'Responsible Supervisor',
  'نسبة إنجاز المستهدف:': 'Target Completion Rate:',
  'الفعلي:': 'Actual:',
  '/ المستهدف:': '/ Target:',
  'توزيع حصص العمالة المشاركة (حسب السجل الميداني)': 'Worker Shares Distribution (per field record)',
  'اسم العامل': 'Worker Name',
  'الكود': 'Code',
  'الكمية الفردية': 'Individual Quantity',
  'ساعات العمل': 'Work Hours',

  // ============================================================
  // PRODUCTION FORM
  // ============================================================
  'يرجى ملء جميع الحقول الإجبارية': 'Please fill all required fields',
  'فشل حفظ تقرير الإنتاج اليومي': 'Failed to save daily production report',
  'إدخال تقرير إنتاجية يومي مرحلي جديد': 'Enter New Staged Daily Productivity Report',
  'حفظ تقرير الإنتاج (مسودة)': 'Save Production Report (Draft)',
  'تاريخ التنفيذ *': 'Execution Date *',
  'الفرع *': 'Branch *',
  'المشروع *': 'Project *',
  'اختر المشروع...': 'Select project...',
  'بند العمل *': 'Work Item *',
  'اختر بند العمل...': 'Select work item...',
  'مرحلة البند المنفذة * (المعدل القياسي التلقائي)': 'Executed Item Stage * (Automatic Standard Rate)',
  '— (وزن:': '— (Weight:',
  '% | إنتاجية قياسية:': '% | Standard productivity:',
  'منطقة / موقع العمل (اختياري)': 'Work Area / Site (Optional)',
  '(كامل المشروع / بدون تحديد منطقة)': '(Entire project / No specific area)',
  'المشرف الميداني المسؤول *': 'Responsible Field Supervisor *',
  'اختر المشرف...': 'Select supervisor...',
  'الكمية المستهدفة (Target) *': 'Target Quantity *',
  'الكمية الفعلية المنفذة (Actual) *': 'Actual Executed Quantity *',
  'نمط تسجيل الإنتاجية *': 'Productivity Recording Mode *',
  'فردي (حسب إنجاز كل عامل - Rule R5)': 'Individual (per worker completion - Rule R5)',
  'فريق عمل جماعي (Team)': 'Team Work',
  'كود / اسم الفريق الجماعي *': 'Team Code / Name *',
  'مثال: TEAM-PLASTER-01': 'Example: TEAM-PLASTER-01',
  'توزيع إنجاز العمال المشاركين (Rule R5 + إضافي وحوافز)': 'Participating Workers Completion Distribution (Rule R5 + Overtime & Incentives)',
  'مجموع كميات العمال (': 'Total worker quantities (',
  ') يجب أن يطابق تمامًا الكمية الفعلية (': ') must exactly match the actual quantity (',
  'إضافة عامل': 'Add Worker',
  'ساعات أساسية': 'Basic Hours',
  'ساعات العمل الأساسية (8)': 'Basic Work Hours (8)',
  'إضافي (ساعة)': 'Overtime (hour)',
  'ساعات العمل الإضافية (Overtime)': 'Overtime Work Hours',
  'حافز %': 'Incentive %',
  'نسبة الحافز أو المكافأة %': 'Incentive or bonus percentage %',
  'المستوى المهني': 'Professional Level',
  'فني (صنايعي)': 'Technician (Skilled)',
  'مساعد (عامل)': 'Assistant (Worker)',
  'حذف العامل': 'Remove Worker',

  // ============================================================
  // PRODUCTION LIST
  // ============================================================
  'فشل تحميل سجلات الإنتاج اليومي': 'Failed to load daily production records',
  'تم تصدير ملف إنتاجية الإكسيل بنجاح': 'Productivity Excel file exported successfully',
  'فشل تصدير ملف الإنتاجية': 'Failed to export productivity file',
  'إجمالي السجلات (الشهر)': 'Total Records (Month)',
  'متوسط نسبة الإنجاز': 'Average Completion Rate',
  'معتمد نهائياً ومغلق': 'Final Approved & Closed',
  'جاهز للحسابات والحوافز': 'Ready for calculations and incentives',
  'بانتظار الاعتماد': 'Awaiting Approval',
  'مسودة (Draft)': 'Draft',
  'مقدم (Submitted)': 'Submitted',
  'معتمد مشرف': 'Supervisor Approved',
  'معتمد مهندس': 'Engineer Approved',
  '✓ معتمد نهائيًا': '✓ Final Approved',
  'بحث (بند/مشروع/مشرف)': 'Search (item/project/supervisor)',
  'حالة الاعتماد': 'Approval Status',
  'معتمد نهائيًا': 'Final Approved',
  'المشروع / الفرع': 'Project / Branch',
  'البند والمرحلة': 'Item & Stage',
  'النوع والفريق': 'Type & Team',
  'المستهدف': 'Target',
  'الفعلي': 'Actual',
  'لا توجد سجلات إنتاجية مطابقة لمعايير البحث': 'No productivity records matching search criteria',
  'فريق (': 'Team (',
  'فردي (': 'Individual (',
  'عمال)': 'workers)',
  'عرض التفاصيل ومسار الاعتماد': 'View Details & Approval Path',
  'الفعلي / المستهدف': 'Actual / Target',
  'عرض التفاصيل والاعتماد': 'View Details & Approve',
  'سجل إنتاجية': 'Productivity Record',
  'من': 'from',
  'تم تسجيل تقرير الإنتاجية بنجاح!': 'Productivity report recorded successfully!',
  'تم تقديم طلب التصحيح بنجاح!': 'Correction request submitted successfully!',
  'تم استيراد واعتماد سجلات الإنتاج بنجاح!': 'Production records imported and approved successfully!',
  'فشل رفع ومعالجة ملف إنتاجية الإكسيل': 'Failed to upload and process productivity Excel file',
  'تم اعتماد وإدراج سجلات الإنتاج الصالحة بنجاح!': 'Valid production records approved and inserted successfully!',
  'فشل اعتماد سجلات الإنتاج': 'Failed to approve production records',
  'استيراد سجلات الإنتاجية من ملف Excel (.xlsx)': 'Import Productivity Records from Excel (.xlsx)',
  'رفع ومعاينة الإنتاج': 'Upload & Preview Production',
  'اختر ملف سجلات الإنتاج (.xlsx) للرفع والمعاينة': 'Select production records file (.xlsx) for upload and preview',
  'يتم فحص المشاريع والبنود وتوزيع الكميات وتوليد تقرير مرحلي قبل الاعتماد النهائي': 'Projects, items and quantity distributions are checked and a staged report is generated before final approval',

  // ============================================================
  // PROJECTS
  // ============================================================
  'تعديل بيانات المشروع': 'Edit Project Data',
  'إنشاء مشروع جديد': 'Create New Project',
  'إنشاء المشروع': 'Create Project',
  'اسم المشروع *': 'Project Name *',
  'مثال: تشطيبات برج الرياض التجاري': 'Example: Riyadh Commercial Tower finishing works',
  'الفرع التابع *': 'Parent Branch *',
  'كود المشروع': 'Project Code',
  'مثال: PRJ-RYD-01': 'Example: PRJ-RYD-01',
  'حالة المشروع': 'Project Status',
  'قيد التنفيذ (In Progress)': 'In Progress',
  'مخطط له (Planned)': 'Planned',
  'مكتمل (Completed)': 'Completed',
  'معلق (On Hold)': 'On Hold',
  'قيمة العقد (SAR)': 'Contract Value (SAR)',
  'تاريخ البدء': 'Start Date',
  'تاريخ البدء...': 'Start date...',
  'تاريخ الانتهاء المتوقع': 'Expected End Date',
  'وصف المشروع وملاحظات التعاقد': 'Project Description & Contract Notes',
  'تفاصيل العقد والموقع...': 'Contract and site details...',
  'فشل تحميل بيانات المشاريع': 'Failed to load project data',
  'تم تحديث المشروع بنجاح': 'Project updated successfully',
  'تم إنشاء المشروع بنجاح': 'Project created successfully',
  'فشل حفظ بيانات المشروع': 'Failed to save project data',
  'فشل حذف المشروع': 'Failed to delete project',
  '⚡ قيد التنفيذ': '⚡ In Progress',
  '🗓️ مخطط له': '🗓️ Planned',
  '⏸️ معلق': '⏸️ On Hold',
  'إجمالي المشاريع': 'Total Projects',
  'مشاريع قيد التنفيذ': 'Projects In Progress',
  'مواقع إنتاجية نشطة': 'Active production sites',
  'مشاريع مكتملة ومسلّمة': 'Completed & Delivered Projects',
  'إجمالي قيمة العقود': 'Total Contract Value',
  'لكافة المشاريع المسجلة': 'For all registered projects',
  'بحث باسم المشروع أو الكود': 'Search by project name or code',
  'فلترة بحسب الفرع التابع': 'Filter by parent branch',
  'مخطط له': 'Planned',
  'المشروع / الكود': 'Project / Code',
  'الفرع التابع': 'Parent Branch',
  'تاريخ البدء والانتهاء': 'Start & End Date',
  'لا توجد مشاريع مسجلة مطابقة للبحث': 'No projects matching search found',
  'إلى': 'to',
  'مفتوح': 'Open',
  'تعديل المشروع': 'Edit Project',
  'حذف المشروع': 'Delete Project',
  'تأكيد حذف المشروع': 'Confirm Project Deletion',
  'هل أنت متأكد من رغبتك في حذف المشروع': 'Are you sure you want to delete the project',

  // ============================================================
  // RBAC / PERMISSIONS
  // ============================================================
  'المقايسة وتقدم التنفيذ (BOQ)': 'BOQ & Execution Progress',
  'التنبيهات الميدانية': 'Field Alerts',
  'إدارة المستخدمين والحسابات': 'User & Account Management',
  'مصفوفة الصلاحيات (RBAC)': 'Permissions Matrix (RBAC)',
  'إعدادات النظام والمنشأة': 'System & Company Settings',
  'فشل تحميل بيانات مصفوفة الصلاحيات والأدوار': 'Failed to load permissions matrix and roles data',
  'فشل حفظ الصلاحيات': 'Failed to save permissions',
  'جاري تحميل مصفوفة الصلاحيات والأدوار...': 'Loading permissions matrix and roles...',
  'إجمالي الأدوار:': 'Total Roles:',
  'إجمالي الصلاحيات:': 'Total Permissions:',
  'الأدوار الوظيفية (Roles)': 'Job Roles',
  'أدوار': 'Roles',
  'غير محفوظ': 'Unsaved',
  'تحديد الصلاحيات الممنوحة لهذا الدور في مختلف وحدات النظام': 'Set permissions granted to this role across system modules',
  'تفعيل الكل': 'Enable All',
  'إلغاء الكل': 'Disable All',
  'إلغاء التغييرات واستعادة الوضع المحفوظ': 'Undo changes and restore saved state',
  'تراجع': 'Undo',
  'تم الحفظ': 'Saved',
  'ابحث في أسماء الصلاحيات أو الرموز البرمجية (مثل: production.approve, users.create)...': 'Search permission names or codes (e.g.: production.approve, users.create)...',
  'مسح': 'Clear',
  'لا توجد صلاحيات مطابقة لكلمة البحث "': 'No permissions matching search term "',
  'حساس': 'Sensitive',

  // ============================================================
  // DAILY REPORT
  // ============================================================
  'تعذر تحميل التقرير اليومي': 'Failed to load daily report',
  'الوزن %': 'Weight %',
  'المكافئ الموزون': 'Weighted Equivalent',
  'عدد العمال': 'Worker Count',
  'تكلفة العمالة (SAR)': 'Labor Cost (SAR)',
  'الإنتاجية القياسية': 'Standard Productivity',
  'نسبة الإنجاز %': 'Completion Rate %',
  'تصدير ملف Excel / CSV': 'Export Excel / CSV File',
  'اختر المشروع': 'Select Project',
  'تاريخ العمل اليومي': 'Daily Work Date',
  'إجمالي الكميات المنفذة': 'Total Executed Quantities',
  'المكافئ الموزون النهائي': 'Final Weighted Equivalent',
  'إجمالي العمال المشتركين': 'Total Participating Workers',
  'تكلفة عمالة اليوم': 'Today\'s Labor Cost',
  'جاري تجميع بيانات التقرير اليومي...': 'Compiling daily report data...',
  'لا توجد سجلات إنتاج مسجلة لهذا المشروع في تاريخ': 'No production records registered for this project on date',
  'البند وكوده': 'Item & Code',
  'المرحلة المنفذة': 'Executed Stage',
  'تكلفة العمالة': 'Labor Cost',
  'الإنتاجية vs القياسي': 'Productivity vs Standard',
  'وزن:': 'Weight:',
  'الإجمالي لليوم:': 'Daily Total:',

  // ============================================================
  // SAVED REPORTS
  // ============================================================
  'فشل تحميل التقارير المحفوظة': 'Failed to load saved reports',
  'اسم التقرير مطلوب': 'Report name is required',
  'تم تحديث التقرير المحفوظ بنجاح.': 'Saved report updated successfully.',
  'تم إنشاء وحفظ التقرير الجديد بنجاح.': 'New report created and saved successfully.',
  'فشل حفظ التقرير': 'Failed to save report',
  'فشل تشغيل التقرير': 'Failed to run report',
  'تم تحديث صلاحيات مشاركة التقرير بنجاح.': 'Report sharing permissions updated successfully.',
  'فشل مشاركة التقرير': 'Failed to share report',
  'فشل حذف التقرير': 'Failed to delete report',
  'إنتاجية ميدانية': 'Field Productivity',
  'حضور وغياب': 'Attendance & Absence',
  'تكاليف ومصروفات': 'Costs & Expenses',
  'مستخلصات BOQ': 'BOQ Extracts',
  'إجمالي التقارير المحفوظة': 'Total Saved Reports',
  'تقارير الإنتاجية والأداء': 'Productivity & Performance Reports',
  'تحليلات الإنجاز اليومي': 'Daily Completion Analytics',
  'تقارير الحضور والتكاليف': 'Attendance & Cost Reports',
  'مراقبة المصاريف والعمالة': 'Expense & Labor Monitoring',
  'تقارير عامة مشتركة للشركة': 'Shared Company Reports',
  'متاحة لجميع مدراء المشاريع': 'Available to all project managers',
  'التقارير المحفوظة والمخصصة (Saved Reports)': 'Saved & Custom Reports',
  'بناء تقارير ديناميكية مخصصة بمرشحات مختلفة، تشغيلها دورياً ومشاركتها مع فريق الإدارة': 'Build custom dynamic reports with different filters, run them periodically and share with management team',
  'إنشاء قالب تقرير جديد': 'Create New Report Template',
  'تصفية بحسب نوع التقرير': 'Filter by Report Type',
  'كافة أنواع التقارير': 'All Report Types',
  'مستخلصات المقايسة': 'BOQ Extracts',
  'اسم التقرير': 'Report Name',
  'نوع التقرير': 'Report Type',
  'الصلاحية والمشاركة': 'Permissions & Sharing',
  'تاريخ الإنشاء': 'Creation Date',
  'لا توجد تقارير محفوظة مطابقة للاختيار': 'No saved reports matching selection',
  'عام للشركة': 'Company-wide',
  'خاص / محدد': 'Private / Specific',
  'تشغيل التقرير واستعراض البيانات': 'Run Report & View Data',
  'تشغيل': 'Run',
  'مشاركة التقرير': 'Share Report',
  'تعديل القالب': 'Edit Template',
  'حذف التقرير': 'Delete Report',
  'تقرير محفوظ': 'Saved Report',
  'تعديل قالب التقرير': 'Edit Report Template',
  'إنشاء وحفظ قالب تقرير جديد': 'Create & Save New Report Template',
  'حفظ التقرير': 'Save Report',
  'مثال: التقرير الأسبوعي للإنتاجية - فرع الرياض': 'Example: Weekly Productivity Report - Riyadh Branch',
  'نوع التقرير ومصدر البيانات': 'Report Type & Data Source',
  'إنتاجية ومخرجات الموقع (Production)': 'Site Productivity & Output',
  'الحضور والانصراف والإضافي (Attendance)': 'Attendance & Overtime',
  'التكاليف والمصروفات المحاسبية (Costs)': 'Accounting Costs & Expenses',
  'بطاقات التحكم والربحية (Control Cards)': 'Control Cards & Profitability',
  'تقدم بنود المقايسة (BOQ Progress)': 'BOQ Progress',
  'تقرير عام متاح لكافة مستخدمي الشركة': 'General report available to all company users',
  'جاري تشغيل الاستعلام واستخراج البيانات...': 'Running query and extracting data...',
  'عدد السجلات المستخرجة:': 'Extracted records count:',
  'تاريخ التشغيل:': 'Run date:',
  'لا توجد سجلات مستخرجة مطابقة لشروط التقرير': 'No extracted records matching report conditions',
  'حفظ المشاركة': 'Save Sharing',
  'معرفات المستخدمين المصرح لهم (مفصولة بفواصل)': 'Authorized user IDs (comma-separated)',
  'اترك الحقل فارغاً إذا كان التقرير متاحاً للعامة': 'Leave empty if the report is publicly available',
  'تأكيد حذف التقرير المحفوظ': 'Confirm Saved Report Deletion',
  'هل أنت متأكد من رغبتك في حذف قالب التقرير': 'Are you sure you want to delete the report template',

  // ============================================================
  // SETTINGS
  // ============================================================
  'شركة ساكوديكو للمقاولات العامة (SACODECO)': 'SACODECO General Contracting Co.',
  'SAR - ريال سعودي': 'SAR - Saudi Riyal',
  'المملكة العربية السعودية (KSA)': 'Kingdom of Saudi Arabia (KSA)',
  'الرياض - حي الملز - طريق صلاح الدين الأيوبي': 'Riyadh - Al Malaz District - Salahuddin Road',
  'فشل تحميل معدلات أجور العمالة': 'Failed to load labor wage rates',
  'تم حفظ وتحديث بيانات الشركة والإعدادات العامة بنجاح.': 'Company data and general settings saved and updated successfully.',
  'تم حفظ وتحديث جميع معاملات المعادلات الرياضية والتشغيلية بنجاح!': 'All mathematical and operational equation parameters saved and updated successfully!',
  'فشل حفظ معاملات الحساب': 'Failed to save calculation parameters',
  'تم تحديث معدل الأجر بنجاح.': 'Wage rate updated successfully.',
  'تم إضافة معدل الأجر الجديد بنجاح.': 'New wage rate added successfully.',
  'فشل حفظ معدل الأجر': 'Failed to save wage rate',
  'ساعات العمل العادية (Normal)': 'Normal Work Hours',
  'عطلات ونهاية الأسبوع (Weekend)': 'Holidays & Weekends',
  'أجر الإشراف الميداني (Supervisor)': 'Field Supervision Wage',
  'الإنتاجية اليومية والمراحل (Production)': 'Daily Productivity & Stages',
  'التكاليف والمصروفات (Costs & Expenses)': 'Costs & Expenses',
  'الحوافز والمكافآت (Incentives Engine)': 'Incentives & Bonuses Engine',
  'المقايسة وتقدم التنفيذ (BOQ Progress)': 'BOQ & Execution Progress',
  'الأرشيف والمستندات (Documents Archive)': 'Archive & Documents',
  'إعدادات المنظومة والأسعار (Settings & Rates)': 'System Settings & Rates',
  'المنشأة والمقر': 'Company & Headquarters',
  'المملكة العربية السعودية': 'Kingdom of Saudi Arabia',
  'العملة المحاسبية المعتمدة': 'Approved Accounting Currency',
  'ريال سعودي': 'Saudi Riyal',
  'فئات معدلات الأجور': 'Wage Rate Categories',
  'تُطبق آليًا على الحضور': 'Automatically applied to attendance',
  'المستخدم الحالي': 'Current User',
  'مدير النظام': 'System Admin',
  'بيانات الشركة والمنظومة': 'Company & System Data',
  'معدلات وتسعير أجور العمالة (': 'Labor Wage Rates & Pricing (',
  'المستخدمون ومصفوفة الصلاحيات (RBAC)': 'Users & Permissions Matrix (RBAC)',
  'معادلات الحساب والتشغيل (Calculation Settings)': 'Calculation & Operation Settings',
  'اسم الشركة الرسمي': 'Official Company Name',
  'رقم السجل التجاري (CR Number)': 'Commercial Registration No. (CR)',
  'الرقم الضريبي (VAT / Tax ID)': 'Tax Number (VAT / Tax ID)',
  'العملة المحاسبية الرئيسية': 'Main Accounting Currency',
  'الدولة والمنطقة': 'Country & Region',
  'النطاق الزمني والتوقيت': 'Timezone & Timing',
  'العنوان والمقر الرئيسي': 'Address & Headquarters',
  'هاتف التواصل': 'Contact Phone',
  'البريد الإلكتروني الرسمي': 'Official Email',
  'حفظ التعديلات العامة': 'Save General Settings',
  'جدول تسعير ومعدلات ساعات وأيام العمل': 'Work Hours & Days Pricing Schedule',
  'تُستخدم هذه المعدلات لاحتساب تكاليف الأجور تلقائيًا من واقع سجلات الحضور الميداني': 'These rates are used to automatically calculate wage costs from field attendance records',
  'إضافة معدل أجر': 'Add Wage Rate',
  'فئة ونوع الأجر': 'Wage Category & Type',
  'الأجر بالساعة (SAR/Hour)': 'Hourly Wage (SAR/Hour)',
  'الأجر اليومي (SAR/Day)': 'Daily Wage (SAR/Day)',
  'تاريخ بدء السريان': 'Effective Start Date',
  'لا توجد معدلات أجور مسجلة': 'No wage rates registered',
  'تعديل المعدل': 'Edit Rate',
  'اسم المستخدم:': 'Username:',
  '• معرف النظام:': '• System ID:',
  'مصفوفة صلاحيات الأدوار القياسية (RBAC Matrix)': 'Standard Role Permissions Matrix (RBAC)',
  'توزيع صلاحيات الوصول والتعديل عبر وحدات النظام بحسب المسمى الوظيفي': 'Access and edit permissions distribution across system modules by job title',
  'الوحدة / الشاشة': 'Module / Screen',
  'مدير النظام (Admin)': 'System Admin',
  'مدير المشروع (PM)': 'Project Manager (PM)',
  'المشرف الميداني (Supervisor)': 'Field Supervisor',
  'المحاسب المالي (Accountant)': 'Financial Accountant',
  'معاملات المعادلات الحسابية والتشغيلية (Dynamic Calculation Parameters)': 'Mathematical & Operational Equation Parameters',
  'جميع الأرقام والمعادلات في النظام هي قيم ابتدائية قابلة للتعديل والتحكم الكامل في أي لحظة. لا توجد ثوابت مقدسة.': 'All numbers and formulas in the system are initial values that can be fully edited and controlled at any time. There are no fixed constants.',
  'جاري تحميل الإعدادات...': 'Loading settings...',
  'معايير أوقات وساعات العمل': 'Work Hours & Time Standards',
  'ساعات العمل اليومية القياسية *': 'Standard Daily Work Hours *',
  'ساعة / يوم': 'hour / day',
  'تُستخدم لحساب إنتاجية الساعة الفردية (Daily Target ÷ Crew Hours) وتكلفة أجر الساعة للعمالة.': 'Used to calculate individual hourly productivity (Daily Target ÷ Crew Hours) and hourly wage cost for labor.',
  'معامل احتساب الوقت الإضافي (Overtime Multiplier) *': 'Overtime Calculation Multiplier *',
  'مضاعف (Multiplier)': 'Multiplier',
  'مضاعف أجر الساعة لساعات العمل الإضافية (مثال: 1.5 يعني أجر ساعة ونصف لكل ساعة إضافية).': 'Hourly wage multiplier for overtime hours (example: 1.5 means one and a half hours pay per overtime hour).',
  'دقة الحسابات والتقريب العشري': 'Calculation Precision & Decimal Rounding',
  'دقة التقريب العشري (Rounding Decimals) *': 'Decimal Rounding Precision *',
  'خانات عشرية': 'decimal places',
  '0 خانات (أرقام صحيحة فقط)': '0 places (integers only)',
  '1 خانة عشرية (مثال: 21.5)': '1 decimal place (e.g.: 21.5)',
  '2 خانات عشرية (مثال: 21.60) - قياسي معتمد': '2 decimal places (e.g.: 21.60) - approved standard',
  '3 خانات عشرية (مثال: 21.605)': '3 decimal places (e.g.: 21.605)',
  '4 خانات عشرية (مثال: 21.6052)': '4 decimal places (e.g.: 21.6052)',
  'تُحدد دقة تقريب تكاليف الوحدة، هوامش الربح، والكميات ونسب الإنجاز في بطاقات التحكم والتقارير.': 'Determines rounding precision for unit costs, profit margins, quantities and completion rates in control cards and reports.',
  'تكوين طاقم العمل الافتراضي (Default Crew)': 'Default Crew Composition',
  'عدد الفنيين (المعلمين) *': 'Number of Technicians *',
  'عدد المساعدين (العمال) *': 'Number of Assistants (Workers) *',
  'التركيبة الافتراضية لطاقم العمل في بطاقات التحكم في حال عدم تحديد تكوين مخصص للمرحلة التنفيذية.': 'Default crew composition for control cards when no custom configuration is set for the execution stage.',
  'الإنتاجيات واليوميات القياسية المرجعية': 'Reference Standard Productivity & Daily Rates',
  'معدل الإنتاج القياسي اليومي للبند *': 'Item Standard Daily Production Rate *',
  'وحدة / يوم': 'unit / day',
  'يومية الفني الافتراضية *': 'Default Technician Daily Rate *',
  'يومية المساعد الافتراضية *': 'Default Assistant Daily Rate *',
  'معاينة حية لتطبيق هذه المعاملات على معادلات المنظومة الحالية': 'Live preview of applying these parameters to current system formulas',
  'تكلفة طاقم العمل اليومي': 'Daily Crew Cost',
  'ريال / يوم': 'SAR / day',
  'تكلفة أجر العمالة للوحدة القياسية': 'Standard Unit Labor Cost',
  'ريال / م²': 'SAR / m²',
  'إنتاجية ساعة العمل للفرد الواحد': 'Individual Hourly Productivity',
  'م² / (ساعة · فرد)': 'm² / (hour · person)',
  'أفراد ×': 'members ×',
  'ساعات)': 'hours)',
  'أجر ساعة الإضافي للفني': 'Technician Overtime Hourly Wage',
  'ريال / ساعة': 'SAR / hour',
  'جاري حفظ المعاملات...': 'Saving parameters...',
  'حفظ وتطبيق جميع المعاملات الحسابية': 'Save & Apply All Calculation Parameters',
  'تعديل معدل الأجر': 'Edit Wage Rate',
  'إضافة معدل أجر جديد': 'Add New Wage Rate',
  'حفظ التعديل': 'Save Edit',
  'إضافة المعدل': 'Add Rate',
  'فئة / نوع الأجر': 'Wage Category / Type',
  'الأجر بالساعة (SAR)': 'Hourly Wage (SAR)',
  'الأجر اليومي (SAR)': 'Daily Wage (SAR)',

  // ============================================================
  // TRANSFERS
  // ============================================================
  'تعذر تحميل البيانات': 'Failed to load data',
  'يرجى اختيار الموظف والمشروع المنقول إليه': 'Please select the employee and destination project',
  'فشل إرسال طلب النقل': 'Failed to submit transfer request',
  'طلب نقل كادر أو مشرف ميداني': 'Staff or Field Supervisor Transfer Request',
  'إرسال طلب النقل للمدير': 'Submit Transfer Request to Manager',
  'المشرف أو الكادر المطلوب نقله *': 'Supervisor or Staff to Transfer *',
  'من مشروع (الموقع الحالي)': 'From Project (Current Location)',
  '(التعيين الحالي التلقائي)': '(Current automatic assignment)',
  'إلى مشروع (الموقع المطلوب) *': 'To Project (Requested Location) *',
  'تاريخ التنفيذ المطلوب *': 'Requested Execution Date *',
  'درجة الأهمية والاستعجال': 'Priority & Urgency',
  'عادي (جدولة اعتيادية)': 'Normal (Regular scheduling)',
  'عاجل (على وجه الضرورة القصوى)': 'Urgent (Extremely urgent)',
  'سبب ومبررات طلب النقل *': 'Transfer Request Reason & Justification *',
  'مثال: حاجة ماسة للإشراف على أعمال صب الأسقف والتشطيبات المعقدة...': 'Example: Urgent need for supervision of ceiling casting and complex finishing works...',
  'فشل تحميل سجل طلبات النقل': 'Failed to load transfer requests record',
  'تمت الموافقة على طلب النقل بنجاح': 'Transfer request approved successfully',
  'فشل اعتماد طلب النقل': 'Failed to approve transfer request',
  'يرجى ذكر سبب رفض طلب النقل:': 'Please state the reason for rejecting the transfer request:',
  'تم رفض طلب النقل': 'Transfer request rejected',
  'فشل رفض طلب النقل': 'Failed to reject transfer request',
  'هل تريد تنفيذ النقل الفعلي وتحديث مشروع الكادر في النظام فوراً؟': 'Do you want to execute the actual transfer and update the staff project in the system immediately?',
  'تم تنفيذ النقل الفعلي وتحديث تعيين الكادر بنجاح': 'Actual transfer executed and staff assignment updated successfully',
  'فشل تنفيذ النقل': 'Failed to execute transfer',
  'قيد المراجعة': 'Under Review',
  'معتمد وموافق عليه': 'Approved',
  'تم النقل الفعلي': 'Transfer Executed',
  'حالة الطلب': 'Request Status',
  'قيد المراجعة (Pending)': 'Under Review (Pending)',
  'معتمد (Approved)': 'Approved',
  'تم النقل الفعلي (Executed)': 'Transfer Executed',
  'مرفوض (Rejected)': 'Rejected',
  'درجة الأهمية': 'Priority',
  'كافة الدرجات': 'All Priorities',
  'عاجل (Urgent)': 'Urgent',
  'عادي (Normal)': 'Normal',
  'الكادر / المشرف': 'Staff / Supervisor',
  'من مشروع': 'From Project',
  'إلى مشروع': 'To Project',
  'طالب النقل': 'Transfer Requester',
  'السبب والأهمية': 'Reason & Priority',
  'جاري تحميل طلبات النقل...': 'Loading transfer requests...',
  'لا توجد طلبات نقل مسجلة حالياً': 'No transfer requests registered currently',
  'موافقة على الطلب': 'Approve Request',
  'موافقة': 'Approve',
  'رفض الطلب': 'Reject Request',
  'رفض': 'Reject',
  'تنفيذ النقل الفعلي وتحديث التعيين': 'Execute Transfer & Update Assignment',
  'تنفيذ النقل': 'Execute Transfer',
  'إجمالي طلبات النقل:': 'Total Transfer Requests:',
  'تم تقديم طلب النقل بنجاح وهو قيد مراجعة الإدارة': 'Transfer request submitted successfully and is under management review',

  // ============================================================
  // USERS
  // ============================================================
  'فشل تحميل بيانات المستخدمين': 'Failed to load user data',
  'اسم المستخدم مطلوب': 'Username is required',
  'كلمة المرور يجب أن لا تقل عن 6 أحرف': 'Password must be at least 6 characters',
  'الاسم الكامل مطلوب': 'Full name is required',
  'يرجى اختيار دور وظيفي واحد على الأقل للمستخدم': 'Please select at least one job role for the user',
  'يجب تحديد نطاق مشروع واحد على الأقل للمستخدم الميداني / غير الشامل': 'At least one project scope must be selected for field / non-global users',
  'فشل إنشاء حساب المستخدم': 'Failed to create user account',
  'فشل تحديث بيانات المستخدم': 'Failed to update user data',
  'فشل تعديل حالة الحساب': 'Failed to change account status',
  'فشل تعطيل حساب المستخدم': 'Failed to deactivate user account',
  'فشل جلب استثناءات الصلاحيات': 'Failed to fetch permission overrides',
  'فشل حفظ استثناءات الصلاحيات': 'Failed to save permission overrides',
  'كلمة المرور الجديدة يجب أن لا تقل عن 6 أحرف': 'New password must be at least 6 characters',
  'كلمتا المرور غير متطابقتين': 'Passwords do not match',
  'فشل إعادة تعيين كلمة المرور': 'Failed to reset password',
  'إجمالي حسابات المستخدمين': 'Total User Accounts',
  'الحسابات النشطة': 'Active Accounts',
  'حسابات بنطاق مشاريع محدد': 'Accounts with specific project scope',
  'مديرو النظام الشامل': 'Global System Admins',
  'بحث بالاسم، اسم المستخدم، البريد...': 'Search by name, username, email...',
  'كافة الأدوار الوظيفية': 'All Job Roles',
  'تحديث القائمة': 'Refresh List',
  'تحديث': 'Refresh',
  'جاري تحميل حسابات المستخدمين...': 'Loading user accounts...',
  'لا يوجد مستخدمون مطابقون للبحث': 'No users matching search',
  'يمكنك إنشاء حساب مستخدم جديد أو تعديل خيارات الفلترة.': 'You can create a new user account or adjust filter options.',
  '+ إنشاء حساب جديد': '+ Create New Account',
  'الموظف المرتبط': 'Linked Employee',
  'الأدوار الوظيفية': 'Job Roles',
  'نطاق المشاريع المعزول': 'Isolated Project Scope',
  'غير مرتبط': 'Not Linked',
  'صلاحية شاملة (كافة المشاريع)': 'Full Access (All Projects)',
  'عام (كافة مشاريع الشركة)': 'General (All Company Projects)',
  'انقر لتغيير حالة الحساب': 'Click to change account status',
  'تعديل الأدوار والنطاقات': 'Edit Roles & Scopes',
  'استثناءات الصلاحيات المباشرة': 'Direct Permission Overrides',
  'إعادة تعيين كلمة المرور': 'Reset Password',
  'تعطيل وحذف الجلسات': 'Disable & Delete Sessions',
  'إنشاء حساب مستخدم جديد': 'Create New User Account',
  'ربط بموظف من السجل (اختياري)': 'Link to Employee Record (Optional)',
  '-- بدون ربط بموظف --': '-- No Employee Link --',
  'اسم المستخدم (Username) *': 'Username *',
  'مثال: eng_ahmed': 'Example: eng_ahmed',
  'مثال: م. أحمد خالد': 'Example: Eng. Ahmed Khalid',
  'كلمة المرور * (6 أحرف على الأقل)': 'Password * (6 characters minimum)',
  'البريد الإلكتروني': 'Email',
  'رقم الهاتف': 'Phone Number',
  'الأدوار الوظيفية المعتمدة (Roles) *': 'Approved Job Roles *',
  'مطلوب دور واحد على الأقل': 'At least one role required',
  'نطاق المشاريع المعزول (Project Scope Checklist)': 'Isolated Project Scope Checklist',
  'تحديد كافة المشاريع': 'Select All Projects',
  'إلغاء التحديد': 'Deselect All',
  'الأدوار الإدارية العليا المحددة (Admin / Program Manager) تمنح وصولاً شاملاً لكافة مشاريع وفروع المنشأة تلقائياً.': 'Selected senior administrative roles (Admin / Program Manager) automatically grant full access to all company projects and branches.',
  'فرع:': 'Branch:',
  'المشاريع المحددة:': 'Selected Projects:',
  'الحساب نشط ويمكنه تسجيل الدخول': 'Account is active and can log in',
  'جاري الحفظ...': 'Saving...',
  'إنشاء الحساب': 'Create Account',
  'استثناءات الصلاحيات المباشرة للمستخدم (Permission Overrides)': 'User Direct Permission Overrides',
  'المستخدم:': 'User:',
  'الصلاحيات الفعلية =': 'Effective Permissions =',
  '(صلاحيات الأدوار ∪ استثناءات المنح Grant) ∖ استثناءات الحجب Deny': '(Role Permissions ∪ Grant Overrides) ∖ Deny Overrides',
  'جاري التحميل...': 'Loading...',
  'ممنوحة من الدور': 'Granted by Role',
  '+ منح (Grant)': '+ Grant',
  '- حجب (Deny)': '- Deny',
  'حفظ استثناءات الصلاحيات': 'Save Permission Overrides',
  'كلمة المرور الجديدة *': 'New Password *',
  'تأكيد كلمة المرور الجديدة *': 'Confirm New Password *',
  'تحديث كلمة المرور': 'Update Password',
  'تأكيد تعطيل حساب المستخدم': 'Confirm User Account Deactivation',
  'سيتم إلغاء كافة الجلسات النشطة للمستخدم فوراً': 'All active user sessions will be cancelled immediately',
  'هل أنت متأكد من رغبتك في تعطيل حساب': 'Are you sure you want to deactivate account',
  ')؟ لن يتمكن المستخدم من تسجيل الدخول حتى تتم إعادة تنشيطه.': ')? The user will not be able to log in until reactivated.',

  // ============================================================
  // WORK AREAS
  // ============================================================
  'فشل تحميل مناطق العمل': 'Failed to load work areas',
  'تم تحديث منطقة العمل بنجاح': 'Work area updated successfully',
  'تم إنشاء منطقة العمل بنجاح': 'Work area created successfully',
  'فشل حفظ منطقة العمل': 'Failed to save work area',
  'فشل حذف المنطقة': 'Failed to delete area',
  'إضافة منطقة فرعية تابعة': 'Add Sub-Area',
  'فرعية': 'Sub',
  'تعديل المنطقة': 'Edit Area',
  'حذف المنطقة': 'Delete Area',
  'المشروع الميداني المستهدف *': 'Target Field Project *',
  'إجمالي المناطق المسجلة بالمشروع:': 'Total Areas Registered in Project:',
  'الشجرة الهرمية لمواقع العمل': 'Work Sites Hierarchical Tree',
  'يمكنك طي وفرز المستويات بالضغط على الأسهم': 'You can collapse and sort levels by clicking arrows',
  'جاري بناء الشجرة الهرمية...': 'Building hierarchical tree...',
  'لا توجد مناطق عمل مسجلة لهذا المشروع حتى الآن': 'No work areas registered for this project yet',
  'إضافة أول منطقة رئيسية (مثل: مبنى A)': 'Add first main area (e.g.: Building A)',
  'تعديل منطقة العمل': 'Edit Work Area',
  'إضافة منطقة رئيسية': 'Add Main Area',
  'إنشاء المنطقة': 'Create Area',
  'المنطقة الأب (Parent Area)': 'Parent Area',
  '(منطقة رئيسية - الجذر Root)': '(Main Area - Root)',
  'اسم منطقة العمل *': 'Work Area Name *',
  'مثال: الدور الأرضي / الجناح الشرقي...': 'Example: Ground floor / East wing...',
  'كود المنطقة': 'Area Code',
  'مثال: GF-E1': 'Example: GF-E1',
  'ترتيب العرض (Sort Order)': 'Display Order (Sort Order)',
  'تأكيد حذف منطقة العمل': 'Confirm Work Area Deletion',
  'هل أنت متأكد من رغبتك في حذف المنطقة': 'Are you sure you want to delete the area',
  '؟ سيتم حذف أو فصل كافة المناطق الفرعية التابعة لها.': '? All sub-areas will be deleted or detached.',

  // ============================================================
  // PRICES
  // ============================================================
  'تعذر تحميل بيانات الأسعار': 'Failed to load pricing data',
  'تم تحديث السعر بنجاح': 'Price updated successfully',
  'تم حفظ وتوثيق السعر بنجاح': 'Price saved and documented successfully',
  'تعذر حفظ السعر والتكلفة': 'Failed to save price and cost',
  'تعديل السعر المحدد': 'Edit Selected Price',
  'تحديد أو تحديث أسعار البند': 'Set or Update Item Prices',
  'إلغاء التعديل': 'Cancel Edit',
  'نطاق الفرع': 'Branch Scope',
  'جميع الفروع (السعر القياسي العام)': 'All Branches (General Standard Price)',
  'سعر العقد (ريال) *': 'Contract Price (SAR) *',
  'سعر المواد المعتمد (ريال)': 'Approved Materials Price (SAR)',
  'يومية الفني المعتمدة (ريال/يوم)': 'Approved Technician Daily Rate (SAR/day)',
  'يومية المساعد المعتمدة (ريال/يوم)': 'Approved Assistant Daily Rate (SAR/day)',
  'تاريخ بدء السريان *': 'Effective Start Date *',
  'تحديث السعر': 'Update Price',
  'حفظ وتوثيق السعر': 'Save & Document Price',
  'سجل الأسعار المعتمدة (': 'Approved Price Records (',
  'جاري تحميل الأسعار...': 'Loading prices...',
  'لا توجد أسعار مخصصة لهذا البند بعد. يتم استخدام السعر الافتراضي (': 'No custom prices for this item yet. Using default price (',
  'ريال).': 'SAR).',
  'السعر القياسي العام (لكل الفروع)': 'General Standard Price (All Branches)',
  'يسري من:': 'Effective from:',
  'المواد:': 'Materials:',
  'أجر الفني:': 'Technician wage:',
  'أجر المساعد:': 'Assistant wage:',
  'سعر العقد': 'Contract Price',
  'تعديل السعر': 'Edit Price',

  // ============================================================
  // STAGES
  // ============================================================
  'تعذر تحميل مراحل البند': 'Failed to load item stages',
  'تم تحديث بيانات المرحلة بنجاح': 'Stage data updated successfully',
  'تمت إضافة المرحلة الجديدة بنجاح': 'New stage added successfully',
  'تعذر حفظ المرحلة': 'Failed to save stage',
  'تعذر حذف المرحلة': 'Failed to delete stage',
  'تعذر إعادة ترتيب المراحل': 'Failed to reorder stages',
  'مجموع نسب المراحل التنفيذية:': 'Execution stages percentage total:',
  '✓ مكتمل ومثالي (100%)': '✓ Complete and ideal (100%)',
  '⚠️ تجاوز 100% (تجاوزت الحد)': '⚠️ Exceeded 100% (over limit)',
  'تعديل المرحلة الحالية': 'Edit Current Stage',
  'إضافة مرحلة تنفيذية جديدة': 'Add New Execution Stage',
  'اسم المرحلة التنفيذية *': 'Execution Stage Name *',
  'مثال: البؤج والأوتار، الطرطشة، اللياسة...': 'Example: Guide points, roughcast, plastering...',
  'كود المرحلة (اختياري)': 'Stage Code (Optional)',
  'الوزن النسبي للمرحلة (%) *': 'Stage Relative Weight (%) *',
  'الإنتاجية القياسية اليومية': 'Daily Standard Productivity',
  'مثال: 20': 'Example: 20',
  'تحديث المرحلة': 'Update Stage',
  'إضافة المرحلة': 'Add Stage',
  'المراحل المسجلة (': 'Registered Stages (',
  'جاري تحميل المراحل...': 'Loading stages...',
  'لا توجد مراحل مسجلة لهذا البند بعد. استخدم النموذج أعلاه لإضافة المراحل بنسب متكاملة.': 'No stages registered for this item yet. Use the form above to add stages with integrated percentages.',
  'الإنتاجية القياسية:': 'Standard productivity:',
  'تحريك لأعلى': 'Move Up',
  'تحريك لأسفل': 'Move Down',
  'تعديل المرحلة': 'Edit Stage',
  'حذف المرحلة': 'Delete Stage',

  // ============================================================
  // FINISHING CATEGORIES
  // ============================================================
  'محارة': 'Plastering',
  'لياسة': 'Render',
  'دهان': 'Paint',
  'جبس': 'Gypsum',
  'سيراميك': 'Ceramic',
  'بورسلين': 'Porcelain',
  'رخام': 'Marble',
  'بلك': 'Block',
  'مباني': 'Masonry',
  'نجار': 'Carpentry',
  'ألمنيوم': 'Aluminum',
  'المنيوم': 'Aluminum',
  'كهرب': 'Electrical',
  'سباك': 'Plumbing',
  'تكييف': 'HVAC',
  'عزل': 'Insulation',
  'إيبوكسي': 'Epoxy',
  'ايبوكسي': 'Epoxy',

  // ============================================================
  // WORK ITEMS (BOQ ITEMS)
  // ============================================================
  'فشل تحميل بنود الأعمال': 'Failed to load work items',
  'تم تحديث بند العمل بنجاح': 'Work item updated successfully',
  'تم إنشاء بند العمل بنجاح': 'Work item created successfully',
  'فشل حفظ بند العمل': 'Failed to save work item',
  'فشل حذف بند العمل': 'Failed to delete work item',
  'أقسام التشطيبات (15)': 'Finishing Departments (15)',
  'كافة الأقسام والبنود': 'All Departments & Items',
  'القسم النشط حالياً': 'Currently Active Department',
  'كافة الأقسام': 'All Departments',
  'إجمالي البنود': 'Total Items',
  'متوسط المستهدف اليومي': 'Average Daily Target',
  'المراحل الفرعية المفككة': 'Decomposed Sub-Stages',
  'بحث باسم البند، الكود، أو مواصفات المرحلة': 'Search by item name, code, or stage specifications',
  'مثال: محارة، طرطشة، بؤج، PLS-01...': 'Example: Plastering, roughcast, guide points, PLS-01...',
  'تصفية حسب الفرع': 'Filter by Branch',
  'اسم بند العمل': 'Work Item Name',
  'القسم / الفئة': 'Department / Category',
  'المستهدف اليومي': 'Daily Target',
  'سعر الوحدة': 'Unit Price',
  'المراحل الفرعية': 'Sub-Stages',
  'جاري تحميل بنود ومراحل التشطيبات...': 'Loading finishing items and stages...',
  'لا توجد بنود عمل مسجلة في هذا القسم': 'No work items registered in this department',
  'اضغط على زر "إضافة بند عمل جديد" لإنشاء أول بند في هذا القسم.': 'Click "Add New Work Item" button to create the first item in this department.',
  'إخفاء المراحل': 'Hide Stages',
  'عرض مراحل البند': 'View Item Stages',
  'مراحل (': 'Stages (',
  'تفكيك المراحل': 'Decompose Stages',
  'إدارة مراحل البند والأوزان النسبية': 'Manage Item Stages & Relative Weights',
  'المراحل': 'Stages',
  'إدارة الأسعار والتكلفة': 'Manage Prices & Costs',
  'الأسعار': 'Prices',
  'تعديل البند': 'Edit Item',
  'حذف البند': 'Delete Item',
  'المراحل التنفيذية وتوزيع الأوزان للبند: "': 'Execution Stages & Weight Distribution for Item: "',
  'مجموع الأوزان:': 'Total Weights:',
  '✓ (مكتمل)': '✓ (Complete)',
  '(غير مكتمل 100%)': '(Incomplete 100%)',
  'تعديل / إضافة مراحل': 'Edit / Add Stages',
  'لم يتم تقسيم هذا البند إلى مراحل فرعية بعد. اضغط على "تعديل / إضافة مراحل" لتعريف نسب الإنجاز ومستهدفات كل مرحلة.': 'This item has not been divided into sub-stages yet. Click "Edit / Add Stages" to define completion rates and targets for each stage.',
  'المستهدف القياسي:': 'Standard Target:',
  'حسب المستهدف العام': 'Per General Target',
  'إجمالي بنود العمل:': 'Total Work Items:',
  'تعديل بند عمل': 'Edit Work Item',
  'إضافة بند عمل جديد': 'Add New Work Item',
  'إنشاء البند': 'Create Item',
  'اسم البند *': 'Item Name *',
  'مثال: بياض محارة ولياسة داخلية للغرف والممرات': 'Example: Interior plastering and rendering for rooms and corridors',
  'كود البند': 'Item Code',
  'قسم التشطيبات *': 'Finishing Department *',
  'اختر القسم...': 'Select department...',
  'المستهدف اليومي (م²/يوم)': 'Daily Target (m²/day)',
  'سعر الوحدة التعاقدي (ريال)': 'Contractual Unit Price (SAR)',
  'الفرع (اختياري)': 'Branch (Optional)',
  'وصف البند والمواصفات': 'Item Description & Specifications',
  'تفاصيل التوريد والتركيب والمواصفات الفنية...': 'Supply, installation and technical specification details...',
  'بند نشط ومتاح للاستخدام في المشروعات والمقايسات': 'Item active and available for use in projects and BOQ',
  'تأكيد حذف بند العمل': 'Confirm Work Item Deletion',
  'هل أنت متأكد من حذف بند العمل': 'Are you sure you want to delete this work item',
  'المشروع المستهدف': 'Target Project',
  'سجل': 'Record',
};

// Also include previously mapped entries from translate-master.cjs
const enMapPrev = {
  '* سياسات الحضور تحدد مواعيد الدخول، دقائق السماح، واحتساب الإضافي آلياً وبشكل مرن': '* Attendance policies define entry times, grace minutes, and overtime calculation automatically and flexibly',
  'يتم تطبيق السياسة الأحدث سرياناً على مستوى المشروع، أو السياسة العامة للمنشأة عند عدم التخصيص': 'The latest effective policy is applied at the project level, or the company-wide policy when not customized',
  '🏗️ مخصصة لمشروع:': '🏗️ Specific to project:',
  'قراءة البصمة مجرد "اقتراح حسابي" — كل المعاملات تُستنتج من سياسة الحضور المسجلة بالمنشأة، وكل صف سيكون قابلاً للمعاينة والتعديل البشري الفوري قبل الاعتماد النهائي.': 'Fingerprint reading is just a "computational suggestion" — all transactions are derived from the company\'s registered attendance policy, and each row can be reviewed and manually edited before final approval.',
  'سماح:': 'Grace:',
  'استراحة:': 'Break:',
  '✓ جاهز': '✓ Ready',
  '⚠️ مكرر': '⚠️ Duplicate',
  '✎ معدل يدوياً': '✎ Manually modified',
  'غير صالح': 'Invalid',
  'ملاحظات / سبب التعديل': 'Notes / Edit Reason',
  'لا توجد سجلات مطابقة للفلاتر': 'No records matching the filters',
  'سبب التعديل أو إذن...': 'Edit reason or permission...',
  'تسجيل غياب آلي للموظفين المقيدين بالمشروع والذين لم تظهر بصمتهم في هذا اليوم': 'Auto-register absence for project-assigned employees whose fingerprint was not recorded today',
  'سيتم استبعاد الصفوف غير الصالحة تلقائياً عند الاعتماد': 'Invalid rows will be automatically excluded upon approval',
  'بصمة جهاز': 'Device Fingerprint',
  'الحاضرون اليوم': 'Present Today',
  'تأخيرات الحضور': 'Attendance Delays',
  'تجاوز وقت الوردية والسماح': 'Exceeded shift and grace time',
  'الغياب والتغيب': 'Absences',
  'بدون إذن أو لم يبصموا': 'Without permission or not clocked in',
  'تُحسب في مخصصات الرواتب': 'Counted in salary allowances',
  'وقت الحضور': 'Check-in Time',
  'وقت الانصراف': 'Check-out Time',
  'لا توجد سجلات حضور مسجلة': 'No attendance records found',
  'هوية:': 'ID:',
  'صفحة': 'Page',
  'اختر الموظف...': 'Select employee...',
  'بدون تحديد مشروع': 'Without specifying project',
  'بدون تحديد فرع': 'Without specifying branch',
  'إجازة بعذر (Excused)': 'Excused Leave',
  'تاريخ بدء سريان السياسة *': 'Policy effective start date *',
  'ميعاد بداية الدوام (Shift Start) *': 'Work shift start time *',
  'ميعاد نهاية الدوام (Shift End) *': 'Work shift end time *',
  'فترة السماح بالدقائق (Grace Period)': 'Grace period in minutes',
  'مدة الاستراحة بالدقائق (Break)': 'Break duration in minutes',
  'بدء الإضافي بعد (ساعات عمل صافية)': 'Overtime starts after (net work hours)',
  'تفعيل هذه السياسة فوراً للاستخدام في حسابات الحضور واستيراد البصمات': 'Activate this policy immediately for use in attendance calculations and fingerprint imports',
  'فشل اعتماد واستيراد سجلات البصمة': 'Failed to approve and import fingerprint records',
  'استيراد وتدقيق بصمات الحضور (Biometric Device Attendance)': 'Import & Audit Attendance Fingerprints (Biometric Device)',
  'اعتماد واستيراد (': 'Approve and import (',
  'سجل صالح)': 'valid record)',
  'القاعدة الذهبية:': 'Golden Rule:',
  '✓ تم اختيار الملف (': '✓ File selected (',
  'KB) — انقر للتغيير': 'KB) — click to change',
  'يدعم ملفات أجهزة ZKTeco, Suprema, وغيرها (الصيغة اليومية المباشرة أو سجل الحركات Punch List)': 'Supports ZKTeco, Suprema, and other device files (daily format or Punch List records)',
  'السياسة المطبقة:': 'Applied Policy:',
  '(سارية من': '(Effective from',
  'حالة المطابقة': 'Matching Status',
  'متوسط الإنجاز الكلي': 'Overall Average Completion',
  'محسوبة تراكمياً من الإنتاج الفعلي': 'Calculated cumulatively from actual production',
  'بنود مكتملة بالكامل 100%': 'Items fully completed 100%',
  'وصلت للكمية التعاقدية': 'Reached contractual quantity',
  'مصدر الاحتساب المعتمد': 'Approved calculation source',
  'سجلات معتمدة': 'Approved records',
  'final_approved حصراً': 'final_approved exclusively',
  'تصفية بحسب المشروع': 'Filter by project',
  'رقم البند / التوصيف': 'Item number / Description',
  'الكمية التعاقدية': 'Contractual Quantity',
  'الكمية المنفذة': 'Executed Quantity',
  'الكمية المتبقية': 'Remaining Quantity',
  'لا توجد بنود مقايسة مسجلة لهذا الاختيار': 'No BOQ items registered for this selection',
  'تم إنشاء الفرع الجديد بنجاح': 'New branch created successfully',
  'إجمالي الفروع الإدارية': 'Total Administrative Branches',
  'الفروع النشطة والتشغيلية': 'Active & Operational Branches',
  'تستقبل مشاريع وتكاليف': 'Receiving projects and costs',
  'الفروع المعطلة أو المؤرشفة': 'Disabled or Archived Branches',
  'مغلقة إدارياً': 'Administratively closed',
  'بحث باسم الفرع أو الكود': 'Search by branch name or code',
  'ابحث...': 'Search...',
  'كافة الحالات': 'All Statuses',
  'النشطة فقط': 'Active Only',
  'المعطلة فقط': 'Disabled Only',
  'الموقع / العنوان': 'Location / Address',
  'لا توجد فروع مسجلة مطابقة للبحث': 'No branches matching search found',
  'هاتف:': 'Phone:',
  'غير محدد': 'Not specified',
  'تأكيد الحذف': 'Confirm Deletion',
  '؟ هذا الإجراء لا يمكن التراجع عنه.': '? This action cannot be undone.',
  'اسم الفرع / الإقليم *': 'Branch / Region Name *',
  'مثال: فرع الرياض أو فرع جدة...': 'Example: Riyadh Branch or Jeddah Branch...',
  'كود الفرع الفريد *': 'Unique Branch Code *',
  'مثال: RUH أو JED...': 'Example: RUH or JED...',
  'موقع / عنوان الفرع': 'Branch Location / Address',
  'المدينة، الحي...': 'City, District...',
  'رقم هاتف الفرع': 'Branch Phone Number',
  'فرع نشط ومتاح للعمليات': 'Branch active and available for operations',
  'هذه الوحدة البرمجية قيد التجهيز والتطوير لتوفير أفضل تجربة مستخدم ومطابقة متطلبات العمل بدقة.': 'This module is under development to provide the best user experience and accurately match business requirements.',
  'الوحدة قيد التجهيز والتطوير (Work in Progress)': 'Module Under Development (Work in Progress)',
  'الميزات المخططة لهذه الشاشة:': 'Planned features for this screen:',
  'حالة المحرك الخلفي:': 'Backend Status:',
  'العودة للوحة التحكم': 'Back to Dashboard',
  'التقرير اليومي الشامل': 'Comprehensive Daily Report',
  'تعذر تحميل بطاقة التحكم': 'Failed to load control card',
  'بطاقة التحكم الحية': 'Live Control Card',
  'تعديل الأسعار': 'Edit Prices',
  'إغلاق البطاقة': 'Close Card',
  'جاري تحميل حسابات البطاقة الحية...': 'Loading live card calculations...',
  '1. جدول تفصيل مراحل التنفيذ والأوزان النسبية': '1. Execution stages detail table and relative weights',
  'الوزن النسبي (%)': 'Relative Weight (%)',
  'الإنتاجية القياسية للفرقة': 'Standard Team Productivity',
  'الإنتاجية الفعلية المحسوبة': 'Calculated Actual Productivity',
  'تكوين الفريق': 'Team Composition',
  'فني +': 'Technician +',
  'مساعد': 'Assistant',
  'مستهدف اليوم بالكامل:': 'Full day target:',
  'معدل إنتاج الفرد بالساعة:': 'Individual hourly production rate:',
  '÷ (أفراد الفريق × 8 ساعات عمل)': '÷ (Team members × 8 work hours)',
  '3. تكلفة عمالة الفريق (SAR)': '3. Team Labor Cost (SAR)',
  'يومية الفني + المساعد:': 'Technician + Assistant daily:',
  'يومية الفريق الكامل:': 'Full team daily:',
  'تكلفة عمالة الوحدة (': 'Unit labor cost (',
  '4. التعاقد والهامش المباشر': '4. Contract and Direct Margin',
  'سعر بيع العقد للوحدة:': 'Contract unit selling price:',
  'تكلفة المواد المقدرة:': 'Estimated material cost:',
  'الهامش الصافي للوحدة:': 'Unit net margin:',
  '5. مؤشرات الموقع الحية والمتابعة التراكمية (Live Tracking Engine)': '5. Live Site Indicators and Cumulative Tracking',
  'كمية المقايسة الكلية': 'Total BOQ Quantity',
  'المنجز الموزون المعتمد': 'Approved Weighted Completion',
  '% إنجاز)': '% completion)',
  'متوسط التنفيذ اليومي (آخر 7 أيام)': 'Daily Execution Average (last 7 days)',
  'الأيام المتبقية لإنهاء البند': 'Remaining days to complete item',
  'بالمعدل الميداني الحالي': 'At the current field rate',
  'فشل تحميل بطاقات التحكم': 'Failed to load control cards',
  'بطاقة تحكم نشطة': 'Active control card',
  'كافة الأقسام (': 'All Departments (',
  'بحث باسم البند أو الكود': 'Search by item name or code',
  'ابحث في بطاقات التحكم...': 'Search control cards...',
  'ربط بمشروع لمتابعة التقدم الحي': 'Link to project for live progress tracking',
  '(القيم القياسية العامة للبطاقات)': '(General standard values for cards)',
  'جاري تحميل بطاقات التحكم الحية...': 'Loading live control cards...',
  'لا توجد بطاقات تحكم مطابقة لبحثك': 'No control cards matching your search',
  'تكلفة العمالة/': 'Labor cost/',
  'سعر العقد:': 'Contract price:',
  'الهامش:': 'Margin:',
  'التقدم في المشروع:': 'Project progress:',
  'عرض بطاقة التحكم الحية': 'View Live Control Card',
  'تم تسجيل قيد التكلفة بنجاح': 'Cost entry recorded successfully',
  'فشل حفظ قيد التكلفة': 'Failed to save cost entry',
  'فشل احتساب أجور العمالة': 'Failed to calculate labor wages',
  '👷 أجور عمالة': '👷 Labor Wages',
  '🧱 مواد وخامات': '🧱 Materials & Supplies',
  '🚜 معدات وآليات': '🚜 Equipment & Machinery',
  '🤝 مقاولو باطن': '🤝 Subcontractors',
  '🏢 مصاريف إدارية': '🏢 Administrative Expenses',
  '📌 أخرى': '📌 Other',
  'إجمالي التكاليف المسجلة': 'Total Recorded Costs',
  'تكاليف المواد والخامات': 'Materials & Supplies Costs',
  'أجور العمالة المحتسبة': 'Calculated Labor Wages',
  'مستخرجة من الحضور الميداني': 'Extracted from field attendance',
  'المعدات ومقاولو الباطن': 'Equipment & Subcontractors',
  'آليات ومقاولي تنفيذ': 'Machinery and execution contractors',
  'احتساب أجور العمالة تلقائيًا': 'Auto-calculate labor wages',
  'إضافة قيد تكلفة': 'Add Cost Entry',
  'نوع التكلفة': 'Cost Type',
  'كافة الفئات': 'All Categories',
  'أجور عمالة (Labor)': 'Labor Wages',
  'مواد وخامات (Material)': 'Materials & Supplies',
  'معدات وآليات (Equipment)': 'Equipment & Machinery',
  'مقاولو باطن (Subcontractor)': 'Subcontractors',
  'مصاريف إدارية (Overhead)': 'Administrative Expenses (Overhead)',
  'الوصف والبيان': 'Description',
  'المبلغ (SAR)': 'Amount (SAR)',
  'المسجِّل / المصدر': 'Recorder / Source',
  'لا توجد قيود تكاليف مسجلة': 'No cost entries recorded',
  'قيد نظامي': 'System entry',
  'قيد تكلفة': 'Cost entry',
  'إضافة قيد تكلفة جديد': 'Add New Cost Entry',
  'حفظ القيد': 'Save Entry',
  'البيان / الوصف *': 'Description *',
  'مثال: شراء إسمنت ومواد عزل للموقع': 'Example: Purchase of cement and insulation materials for site',
  'الفئة *': 'Category *',
  '🤝 مقاول باطن': '🤝 Subcontractor',
  'المبلغ الإجمالي (SAR) *': 'Total Amount (SAR) *',
  'احتساب أجور العمالة التلقائي': 'Auto Labor Wage Calculation',
  'تشغيل الاحتساب': 'Run Calculation',
  'يقوم النظام بحساب تكلفة الأجور تلقائيًا من سجلات الحضور وساعات العمل والإضافي لكل موظف وفق المعادلة المعتمدة.': 'The system automatically calculates wage costs from attendance records, work hours, and overtime for each employee according to the approved formula.',
  'المشروع (اختياري)': 'Project (Optional)',
  'مشاريع التنفيذ الميدانية الجارية': 'Ongoing Field Execution Projects',
  'متابعة حالة التقدم الفعلي والميزانيات التقديرية': 'Track actual progress and estimated budgets',
  'لا توجد مشاريع جارية حالياً': 'No ongoing projects currently',
  'قيد التنفيذ': 'In Progress',
  'المركز الرئيسي': 'Head Office',
  'قيمة العقد:': 'Contract Value:',
  'غير محددة': 'Not specified',
  'تحليل ربحية بنود بطاقات التحكم (Control Cards)': 'Control Card Items Profitability Analysis',
  'سعر العقد، تكلفة الوحدة وهامش الربحية التقديري': 'Contract price, unit cost and estimated profit margin',
  'كافة البطاقات': 'All Cards',
  'لا توجد بنود بطاقات تحكم معرفة': 'No control card items defined',
  'سعر العقد (SAR)': 'Contract Price (SAR)',
  'هامش الوحدة (SAR)': 'Unit Margin (SAR)',
  'تنبيهات الموقع النشطة': 'Active Site Alerts',
  'لا توجد تنبيهات غير مقروءة حالياً': 'No unread alerts currently',
  'تنبيه عاجل': 'Urgent Alert',
  'أحدث مخرجات الإنتاجية': 'Latest Productivity Outputs',
  'لا توجد سجلات إنتاجية حديثة': 'No recent productivity records',
  'الوصول السريع للمنظومة': 'Quick Access to System',
  'محرك احتساب وصرف الحوافز': 'Incentive Calculation & Disbursement Engine',
  'أرشيف المخططات والمستندات': 'Drawings & Documents Archive',
  'التقارير المحفوظة والمخصصة': 'Saved & Custom Reports',
  'إعدادات النظام وأجور العمالة': 'System Settings & Labor Wages',
  'عقود ومستندات تعاقدية': 'Contracts & Contractual Documents',
  'يرجى اختيار ملف لرفعه': 'Please select a file to upload',
  'يرجى إدخال عنوان المستند': 'Please enter the document title',
  'تم رفع المستند بنجاح وأرشفته كإصدار أول (v1).': 'Document uploaded successfully and archived as first version (v1).',
  'فشل تحميل إصدارات المستند': 'Failed to load document versions',
  'يرجى اختيار الملف الجديد': 'Please select the new file',
  'فشل رفع الإصدار الجديد': 'Failed to upload new version',
  'إجمالي المستندات المؤرشفة': 'Total Archived Documents',
  'مستندات مرتبطة بمشاريع': 'Project-linked Documents',
  'مخططات وعقود تنفيذية': 'Drawings & Execution Contracts',
  'مستندات بإصدارات متعددة': 'Documents with Multiple Versions',
  'تم تحديثها ومراجعتها (v2+)': 'Updated and reviewed (v2+)',
  'حجم التخزين المستهلك': 'Used Storage Size',
  'مساحة الملفات السحابية': 'Cloud Files Space',
  'تصنيف المستند': 'Document Classification',
  'كافة التصنيفات': 'All Classifications',
  'مخططات ورسومات هندسية': 'Engineering Drawings & Plans',
  'مستخلصات ومطالبات مالية': 'Invoices & Financial Claims',
  'تقارير جودة واختبارات': 'Quality Reports & Tests',
  'عنوان المستند والملف': 'Document Title & File',
  'رقم المستند': 'Document Number',
  'الحجم والتاريخ': 'Size & Date',
  'لا توجد مستندات مسجلة مطابقة للبحث': 'No documents matching search found',
  'عام / غير مقيد': 'General / Unrestricted',
  'سجل الإصدارات': 'Version History',
  'رفع إصدار جديد': 'Upload New Version',
  'بدء الرفع والأرشفة': 'Start Upload & Archive',
  'الملف المراد رفعه': 'File to Upload',
  'عنوان المستند': 'Document Title',
  'مثال: عقد أعمال الحفر والردم - مشروع برج الرياض': 'Example: Excavation contract - Riyadh Tower project',
  'المشروع التابع (اختياري)': 'Associated Project (Optional)',
  'عام / بدون مشروع محدد': 'General / No specific project',
  'رقم المستند / المرجع (اختياري)': 'Document Number / Reference (Optional)',
  'مثال: DOC-2026-0042': 'Example: DOC-2026-0042',
  'ملاحظات وبيان (اختياري)': 'Notes & Description (Optional)',
  'تفاصيل حول محتوى المستند أو شروط الاعتماد...': 'Details about document content or approval conditions...',
  'الإصدار الحالي النشط:': 'Current Active Version:',
  'جاري تحميل الإصدارات...': 'Loading versions...',
  'لا توجد إصدارات مسجلة': 'No versions registered',
  '• تم الرفع:': '• Uploaded:',
  'تحميل هذا الإصدار': 'Download this version',
  'اعتماد ورفع الإصدار v': 'Approve & Upload version v',
  'الملف المحدّث': 'Updated File',
  'ملاحظات وبيان التعديل في هذا الإصدار': 'Notes & change description for this version',
  'مثال: تعديل المخطط الإنشائي وفق ملاحظات الاستشاري...': 'Example: Structural plan modification per consultant notes...',
  'تأكيد حذف المستند': 'Confirm Document Deletion',
  'تأكيد الحذف النهائي': 'Confirm Permanent Deletion',
  'الاسم الكامل *': 'Full Name *',
  'الاسم الثلاثي...': 'Full name...',
  'نوع وثيقة الهوية *': 'ID Document Type *',
  'هوية وطنية سعودية (National ID)': 'Saudi National ID',
  'إقامة مقيم (Iqama)': 'Resident Iqama',
  'جواز سفر (Passport)': 'Passport',
  'رقم الهوية / الإقامة / الجواز *': 'ID / Iqama / Passport Number *',
  'تاريخ انتهاء الإقامة / الجواز *': 'Iqama / Passport Expiry Date *',
  'تاريخ الانتهاء...': 'Expiry date...',
  'سعودي، مصري، هندي...': 'Saudi, Egyptian, Indian...',
  'الفرع الأساسي': 'Primary Branch',
  'اختر الفرع...': 'Select branch...',
  'الدور الوظيفي *': 'Job Role *',
  'عامل مهني (Worker)': 'Skilled Worker',
  'مهندس موقع (Engineer)': 'Site Engineer',
  'مدير مشروع (Project Manager)': 'Project Manager',
  'الأجر اليومي (SAR) *': 'Daily Wage (SAR) *',
  'كود العامل / الرقم الوظيفي': 'Worker Code / Employee Number',
  'كود جهاز البصمة (Device Code)': 'Fingerprint Device Code',
  'DEV-101 أو رقم Enroll': 'DEV-101 or Enroll number',
  'الموظف / العامل على رأس العمل ونشط': 'Employee / Worker is active and on duty',
  'لم يتم العثور على أي موظف بهذا الرقم القومي/الهوية': 'No employee found with this national ID',
  'تم إنشاء سجل الموظف الجديد بنجاح': 'New employee record created successfully',
  'هوية وطنية 🇸🇦': 'National ID 🇸🇦',
  'إقامة مقيم': 'Resident Iqama',
  'جواز سفر': 'Passport',
  'الموظفون النشطون': 'Active Employees',
  'المشرفون والكوادر': 'Supervisors & Staff',
  'متوسط الأجر اليومي': 'Average Daily Wage',
  'لكافة التخصصات والمواقع': 'For all specializations and sites',
  'الإصدار 1.0.0 (Saudi Localization)': 'Version 1.0.0 (Saudi Localization)',
  'منظومة المقاولات': 'Construction System',
  'تبديل القائمة الجانبية': 'Toggle Sidebar',
  'شركة البناء المتقدمة للتطوير والمقاولات': 'Advanced Construction Development & Contracting Co.',
  'مشروع محدد': 'Specific Project',
  'عذرًا! ليس لديك صلاحية للوصول': 'Sorry! You do not have access permission',
  'حسابك الحالي لا يمتلك الصلاحيات المطلوبة لعرض هذه الصفحة. يرجى التواصل مع مدير النظام.': 'Your current account does not have the required permissions to view this page. Please contact the system administrator.',
  'المملكة العربية السعودية 🇸🇦': 'Kingdom of Saudi Arabia 🇸🇦',
  'الإشعارات والتنبيهات': 'Notifications & Alerts',
  'الرئيسية': 'Home',
  'العمال والموظفون': 'Workers & Employees',
  'المشاريع والفروع': 'Projects & Branches',
  'التكاليف وسجل المصروفات': 'Costs & Expense Records',
  'التنبيهات والإشعارات': 'Alerts & Notifications',
  'نظام التشطيبات': 'Finishing System',
  'الصلاحيات والأمان': 'Permissions & Security',
  'إدارة الحسابات': 'Account Management',
  'فشل تشغيل محرك التقييم': 'Failed to run evaluation engine',
  'تم تحديد كافة الإشعارات كمقروءة': 'All notifications marked as read',
  'تم إنشاء قاعدة التنبيه بنجاح': 'Alert rule created successfully',
  'فشل إنشاء قاعدة التنبيه': 'Failed to create alert rule',
  'انخفاض الإنتاجية': 'Low Productivity',
  'اقتراب انتهاء الإقامة/الهوية': 'Iqama/ID Nearing Expiry',
  'غياب غير مبرر': 'Unjustified Absence',
  'تجاوز الميزانية': 'Budget Overrun',
  'تشغيل الفحص الآن': 'Run Check Now',
  'قواعد التنبيه النشطة (': 'Active Alert Rules (',
  'لا توجد قواعد تنبيه مسجلة': 'No alert rules registered',
  'الحد الحرج:': 'Critical Threshold:',
  'غير مقروء': 'Unread',
  'لا توجد إشعارات حالية': 'No current notifications',
  'إنشاء قاعدة تنبيه جديدة': 'Create New Alert Rule',
  'مثال: تنبيه انخفاض الإنتاجية عن 75%': 'Example: Low productivity alert below 75%',
  'نوع القاعدة *': 'Rule Type *',
  'انخفاض الإنتاجية (Low Productivity)': 'Low Productivity',
  'اقتراب انتهاء الإقامة/الهوية (Iqama Expiry)': 'Iqama/ID Nearing Expiry',
  'غياب غير مبرر (Attendance Irregularity)': 'Unjustified Absence',
  'تجاوز ميزانية التكاليف (Cost Overrun)': 'Cost Budget Overrun',
  'قيمة الحد الحرج (Threshold) *': 'Critical Threshold Value *',
  '؟\r\n          سيتم حذف الملف وكافة إصداراته السابقة نهائيًا.': '?\r\n          The file and all its previous versions will be permanently deleted.',
  'فترة السماح:': 'Grace Period:',
};

// Merge both maps
const fullMap = { ...enMapPrev, ...enMap };

// Step 3: Apply translations
let applied = 0;
for (const [key, arVal] of Object.entries(ar.auto || {})) {
  if (fullMap[arVal]) {
    en.auto[key] = fullMap[arVal];
    applied++;
  }
}

console.log(`Applied: ${applied} / ${Object.keys(en.auto).length}`);

// Save
fs.writeFileSync(enFile, JSON.stringify(en, null, 2) + '\n', 'utf8');

// Count remaining
let remaining = 0;
const samples = [];
for (const [key, val] of Object.entries(en.auto || {})) {
  if (/[\u0600-\u06FF]/.test(val)) {
    remaining++;
    if (samples.length < 15) samples.push(val.substring(0, 80));
  }
}
console.log(`Remaining Arabic in en.json: ${remaining}`);
if (samples.length > 0) {
  console.log('Samples of remaining:');
  samples.forEach(s => console.log('  ' + s));
}
